/**
 * 润学导航 · 路径数据集
 *
 * 字段说明见 CONTRIBUTING.md。
 * 所有数据仅供初筛参考，政策随时变动，务必以 official 链接的官方页面为准。
 *
 * 等级编码（用于比较）：
 *   学历 DEG:  0 无 / 1 高中 / 2 大专 / 3 本科 / 4 硕士 / 5 博士
 *   英语 ENG:  0 几乎不会 / 1 日常交流 / 2 雅思5.5 / 3 雅思6.5 / 4 接近母语
 *   学校 UNI:  数字 = 世界排名档位（50 / 100 / 200 / 500 / 9999 表示不限）
 */

const DEG = { none: 0, highschool: 1, college: 2, bachelor: 3, master: 4, phd: 5 };
const ENG = { none: 0, daily: 1, ielts55: 2, ielts65: 3, fluent: 4 };

const DEG_LABEL = ['无学历', '高中', '大专', '本科', '硕士', '博士'];
const ENG_LABEL = ['几乎不会', '日常交流', '雅思 5.5 / CET-6 水平', '雅思 6.5 / 工作可用', '接近母语'];

/**
 * 法语水平。单独建模是因为它能打开一批英语路径打不开的门 ——
 * 尤其是加拿大 Express Entry 的法语类别定向邀请。
 */
const FRA = { none: 0, basic: 1, mid: 2, nclc7: 3 };
const FRA_LABEL = ['不会法语', '入门 (A1–A2)', '中级 (NCLC 5–6)', 'NCLC 7+ / TEF B2 以上'];

/** 学位就读地 —— 部分路径要求学位必须在当地取得（如香港 IANG、英国 PSW）。 */
const STUDY_LOC = {
  cn: '中国大陆',
  hk: '中国香港',
  uk: '英国',
  us: '美国',
  aunz: '澳大利亚 / 新西兰',
  eu: '欧洲大陆',
  other: '其他国家 / 地区',
};

const SKILLS = {
  tech: 'IT / 软件开发',
  engineering: '工程 / 制造',
  healthcare: '医护 / 生物医药',
  finance: '金融 / 会计',
  science: '科研 / 学术',
  education: '教育 / 培训',
  trades: '技工（厨师/电焊/美发/建筑等）',
  business: '管理 / 市场 / 运营',
  arts: '设计 / 媒体 / 创作',
  none: '暂无明确专业技能',
};

const GOALS = {
  fast: '尽快先出去，落脚再说',
  pr: '奔着永居 / 护照去',
  cheap: '预算有限，越便宜越好',
  family: '要带配偶 / 孩子',
  study: '接受再读一个学位',
  remote: '有远程工作 / 想数字游民',
  business: '有创业或投资打算',
};

/**
 * 发达国家 / 地区，用于结果筛选。
 * 采用 IMF「先进经济体」(Advanced Economies) 口径。
 *
 * 注意几个容易有争议的：
 *   阿联酋 —— 人均收入很高，但 IMF 仍归类为新兴与发展中经济体，故不在此列。
 *   中国香港、新加坡 —— 属于先进经济体。
 */
const DEVELOPED = new Set([
  '美国', '加拿大', '英国', '爱尔兰', '德国', '法国', '荷兰', '葡萄牙', '西班牙',
  '日本', '韩国', '新加坡', '中国香港', '澳大利亚', '新西兰',
]);

const TYPE_LABEL = {
  workholiday: '打工度假',
  jobseek: '毕业生找工作签',
  talent: '人才引进',
  skilled: '技术移民',
  work: '工作签证',
  study: '留学转移民',
  nomad: '数字游民',
  invest: '创业 / 投资',
  soft: '软着陆 / 落脚点',
};

/**
 * req 中所有字段都是「门槛」，留空 = 无此要求。
 *   age:[min,max]  minDeg  uniRank  gradWithin(年)  minEng
 *   workExp(年)  jobOffer(bool)  fundsUSD  skills[](满足其一即可)
 *   studyIn: STUDY_LOC 的 key，表示学位必须在该地取得
 */
const PATHWAYS = [
  // ─────────────── 打工度假 / 快速出去 ───────────────
  {
    id: 'nz-whv',
    country: '新西兰', flag: '🇳🇿',
    name: '打工度假签证 (WHV)', nameEn: 'Working Holiday Visa',
    type: 'workholiday',
    duration: '12 个月',
    pr: '本身不通往永居，但可在境内转学签或技术工签',
    req: { age: [18, 30], minDeg: DEG.highschool, minEng: ENG.ielts55, fundsUSD: 3000 },
    quota: '中国大陆每年 1000 个名额，开放即秒光，需要拼手速',
    cost: '签证费约 NZ$470 + 机票 + 押金资金证明',
    difficulty: 3,
    notes: '门槛最低的一条「先出去」路线。要求雅思 5.5（或同等），需体检。名额是最大瓶颈，通常提前几个月蹲开放时间。',
    official: 'https://www.immigration.govt.nz/new-zealand-visas/visas/visa/china-special-work-visa',
  },
  {
    id: 'au-whv462',
    country: '澳大利亚', flag: '🇦🇺',
    name: '打工度假签证 (462)', nameEn: 'Work and Holiday visa (subclass 462)',
    type: 'workholiday',
    duration: '12 个月，满足偏远地区工作可续签',
    pr: '不直接通往永居，但可转雇主担保 / 学签',
    req: { age: [18, 30], minDeg: DEG.college, minEng: ENG.ielts55, fundsUSD: 3500 },
    quota: '中国大陆每年 5000 个名额',
    cost: '签证费约 AUD$680 + 机票 + 资金证明约 AUD$5,000',
    difficulty: 3,
    notes: '中国大陆护照走的是 462 类别（不是 417）。需要大专以上学历或本科在读满 2 年、英语能力证明、中文水平证明。农场 / 服务业工作机会多。',
    official: 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/work-holiday-462',
  },
  {
    id: 'sg-whp',
    country: '新加坡', flag: '🇸🇬',
    name: '打工度假通行证 (WHP)', nameEn: 'Work Holiday Pass',
    type: 'workholiday',
    duration: '6 个月，不可续',
    pr: '不通往永居，属于短期体验',
    req: { age: [18, 25], minDeg: DEG.bachelor, uniRank: 200, minEng: ENG.daily },
    quota: '2000 个在效名额',
    cost: 'S$180 申请费',
    difficulty: 2,
    notes: '只对指定国家/地区院校的在读生或毕业生开放，年龄卡得很死（18–25）。时间短，适合当作了解新加坡就业市场的跳板，期间可无缝面试转 EP。',
    official: 'https://www.mom.gov.sg/passes-and-permits/work-holiday-programme',
  },
  {
    id: 'ge-visafree',
    country: '格鲁吉亚', flag: '🇬🇪',
    name: '免签停留 1 年', nameEn: 'Visa-free stay',
    type: 'soft',
    duration: '365 天，出境再入境可刷新',
    pr: '需另行申请居留，永居路径慢',
    req: {},
    quota: '无',
    cost: '只要机票，生活成本约 US$700–1200/月',
    difficulty: 1,
    notes: '中国护照免签停留一年，几乎零门槛的「先落地」选项。适合远程工作者和过渡期缓冲。注意：这是停留权不是移民路径，长期需转居留许可。',
    official: 'https://geoconsul.gov.ge/en/visaInformation',
  },

  // ─────────────── 毕业生找工作签（QS 名校向） ───────────────
  {
    id: 'uk-hpi',
    country: '英国', flag: '🇬🇧',
    name: '高潜力人才签证 (HPI)', nameEn: 'High Potential Individual visa',
    type: 'jobseek',
    duration: '2 年（博士 3 年）',
    pr: '需在期内转 Skilled Worker，累计 5 年可申永居',
    req: { minDeg: DEG.bachelor, uniRank: 50, gradWithin: 5, minEng: ENG.ielts55, fundsUSD: 1800 },
    quota: '无名额限制',
    cost: '签证费 £822 + 医疗附加费 IHS 每年 £1,035',
    difficulty: 2,
    notes: '不需要雇主担保、不需要工作 offer，纯凭学校血统。认可名单是英国官方每年发布的 Global Universities List（大致对应世界前 50），必须是毕业当年名单上的学校。',
    official: 'https://www.gov.uk/high-potential-individual-visa',
  },
  {
    id: 'jp-jfind',
    country: '日本', flag: '🇯🇵',
    name: 'J-Find 未来创造人才', nameEn: 'J-Find / Future Creation Individual',
    type: 'jobseek',
    duration: '最长 2 年（先给 1 年，可续）',
    pr: '可转工签或高度人才，高度人才最快 1 年拿永居',
    req: { minDeg: DEG.bachelor, uniRank: 100, gradWithin: 5, fundsUSD: 1400 },
    quota: '无名额限制',
    cost: '签证费很低（数千日元），需 20 万日元以上存款证明',
    difficulty: 2,
    notes: '不要求日语、不要求 offer。名校认定看三大排名（QS / THE / 上海交大）中至少两个的前 100。期间可以打工，也可以搞创业准备。日本生活成本相对低是加分项。',
    official: 'https://www.moj.go.jp/isa/publications/materials/nyuukokukanri07_00212.html',
  },
  {
    id: 'nl-orientation',
    country: '荷兰', flag: '🇳🇱',
    name: '找工作年签证 (Zoekjaar)', nameEn: 'Orientation Year / Zoekjaar',
    type: 'jobseek',
    duration: '12 个月',
    pr: '转高技术移民后连续 5 年可申永居',
    req: { minDeg: DEG.master, uniRank: 200, gradWithin: 3, minEng: ENG.ielts65 },
    quota: '无名额限制',
    cost: '约 €228 申请费',
    difficulty: 2,
    notes: '毕业 3 年内的世界前 200 硕博可申。最大好处：在这一年内找到工作转高技术移民时，工资门槛按「毕业生优惠价」算（远低于常规标准），转换非常顺滑。荷兰英语环境好。',
    official: 'https://ind.nl/en/residence-permits/work/orientation-year-highly-educated-persons',
  },
  {
    id: 'hk-ttps',
    country: '中国香港', flag: '🇭🇰',
    name: '高端人才通行证 (高才通)', nameEn: 'Top Talent Pass Scheme',
    type: 'talent',
    duration: '首次 24–36 个月，有工作可续',
    pr: '连续通常居住 7 年可申永久居民',
    req: { minDeg: DEG.bachelor, uniRank: 100 },
    quota: 'C 类（毕业未满 5 年且工作经验不足 3 年）设年度配额，A/B 类不设限',
    cost: '签证费约 HK$600，几乎零成本',
    difficulty: 1,
    notes: '润学性价比之王。B 类：QS100 本科 + 过去 5 年内有 3 年工作经验，不限毕业年份；C 类：QS100 本科毕业 5 年内但经验不足 3 年，有年度配额。A 类走高收入（年薪 250 万港币以上）。不需要 offer、不需要英语考试、不用离开中文环境。',
    official: 'https://www.immd.gov.hk/eng/services/visas/TTPS.html',
  },
  {
    id: 'hk-qmas',
    country: '中国香港', flag: '🇭🇰',
    name: '优秀人才入境计划 (优才)', nameEn: 'QMAS',
    type: 'talent',
    duration: '首次通常 24–36 个月',
    pr: '住满 7 年可申永久居民',
    req: { age: [18, 50], minDeg: DEG.bachelor, minEng: ENG.daily },
    quota: '配额安排以入境处最新公告为准',
    cost: '申请费低，但需要材料准备成本',
    difficulty: 3,
    notes: '综合计分制：年龄、学历、工作经验、语言、家庭背景全都算分。不要求 QS100，双非本科 + 好工作经历也有机会。适合高才通够不着但工作履历漂亮的人。',
    official: 'https://www.immd.gov.hk/eng/services/visas/quality_migrant_admission_scheme.html',
  },
  {
    id: 'kr-d10',
    country: '韩国', flag: '🇰🇷',
    name: 'D-10 求职签证', nameEn: 'D-10 Job Seeking Visa',
    type: 'jobseek',
    duration: '6 个月一次，最长累计 2 年',
    pr: '需转 E-7 工签，再走积分制居留',
    req: { minDeg: DEG.bachelor, fundsUSD: 3000 },
    quota: '无',
    cost: '申请费低',
    difficulty: 3,
    notes: '积分制（学历、年龄、韩语 TOPIK、工作经验等）。韩国本地毕业生转 D-10 更容易。韩语能力对找工作影响很大，纯英语环境岗位有限。',
    official: 'https://www.visa.go.kr/',
  },
  {
    id: 'de-chancenkarte',
    country: '德国', flag: '🇩🇪',
    name: '机会卡 (Chancenkarte)', nameEn: 'Opportunity Card',
    type: 'jobseek',
    duration: '12 个月，可延长',
    pr: '转工签后 21–33 个月可申永居（视德语水平）',
    req: { minDeg: DEG.college, minEng: ENG.ielts55, fundsUSD: 14000 },
    quota: '无',
    cost: '签证费约 €75 + 资金证明约 €13,000（封锁账户）',
    difficulty: 3,
    notes: '2024 年新政，积分制（学历、工作经验、德语/英语、年龄、是否有德国经历）满 6 分即可。也接受被认可的职业资格（技工路线），不一定要本科。找工作期间每周可打工 20 小时。',
    official: 'https://www.make-it-in-germany.com/en/visa-residence/types/opportunity-card',
  },
  {
    id: 'fr-rece',
    country: '法国', flag: '🇫🇷',
    name: '毕业生找工作居留 (RECE)', nameEn: 'Recherche d\'emploi ou création d\'entreprise',
    type: 'jobseek',
    duration: '12 个月，不可续',
    pr: '需转人才护照或工签，5 年可申永居',
    req: { minDeg: DEG.master, gradWithin: 4, minEng: ENG.daily, studyIn: 'eu' },
    quota: '无',
    cost: '约 €225',
    difficulty: 3,
    notes: '主要面向法国本地院校硕士毕业生；部分情况下认可法国高校在境外的合作学位。法语能力对找工作影响很大。',
    official: 'https://www.service-public.fr/particuliers/vosdroits/F16922',
  },

  // ─────────────── 技术移民（直接奔永居） ───────────────
  {
    id: 'ca-ee',
    country: '加拿大', flag: '🇨🇦',
    name: '快速通道 (Express Entry)', nameEn: 'Express Entry',
    type: 'skilled',
    duration: '直接给永久居民身份',
    pr: '本身就是永居，住满约 3 年可入籍',
    req: { age: [18, 45], minDeg: DEG.bachelor, minEng: ENG.ielts65, workExp: 1 },
    quota: '按 CRS 分数排队捞人，分数线浮动',
    cost: 'CAD$1,525/人 + 语言考试 + 学历认证 + 资金证明约 CAD$14,000',
    difficulty: 4,
    notes: '一步到位拿枫叶卡，含金量高但竞争激烈。CRS 打分：年龄（29 岁前满分）、学历、雅思（CLB9 分数飞涨）、工作经验、法语加分（近年法语类别捞人分数极低，是重要捷径）。境内工作经验（CEC）比境外申请优势大得多。',
    official: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry.html',
  },
  {
    id: 'ca-ee-french',
    country: '加拿大', flag: '🇨🇦',
    name: 'Express Entry 法语类别定向邀请', nameEn: 'Express Entry — French-language proficiency category',
    type: 'skilled',
    duration: '直接给永久居民身份',
    pr: '本身就是永居，住满约 3 年可入籍',
    req: { age: [18, 45], minDeg: DEG.bachelor, minFrench: FRA.nclc7, workExp: 1 },
    quota: '法语类别是近年定向邀请中占比最大的一类',
    cost: '与常规 EE 相同，另加 TEF/TCF 考试费约 CAD$400',
    difficulty: 3,
    notes: '被严重低估的一条路。法语四项都达到 NCLC 7（约 TEF B2）就能进入法语定向池，而法语类别的分数线常年显著低于常规轮次——同样的背景，法语能让你不必去拼那些几乎摸不到的高分。英语不是硬门槛（法语即可满足官方语言要求），有英语成绩则额外加分。代价是从零学到 B2 通常要 1–2 年。注意这条路不要求你去魁北克，魁省有自己独立的移民体系。',
    official: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry/submit-profile/rounds-invitations/category-based-selection.html',
  },
  {
    id: 'au-skilled',
    country: '澳大利亚', flag: '🇦🇺',
    name: '技术移民 189 / 190 / 491', nameEn: 'Skilled Migration',
    type: 'skilled',
    duration: '189/190 直接永居；491 为 5 年临居转永居',
    pr: '是',
    req: { age: [18, 44], minDeg: DEG.bachelor, minEng: ENG.ielts65, workExp: 3 },
    quota: '按职业清单 + EOI 分数邀请',
    cost: 'AUD$4,765 起 + 职业评估 + 语言考试，总计常超 AUD$10,000',
    difficulty: 4,
    notes: '核心是职业评估：你的专业必须在 MLTSSL/STSOL 清单上并通过对应机构评估。分数 65 起步但实际邀请分常年 85+。IT、护理、工程、技工是主力职业。州担保（190）和偏远地区（491）可降分。',
    official: 'https://immi.homeaffairs.gov.au/visas/working-in-australia/skillselect',
  },
  {
    id: 'nz-smc',
    country: '新西兰', flag: '🇳🇿',
    name: '技术移民 (SMC)', nameEn: 'Skilled Migrant Category',
    type: 'skilled',
    duration: '直接永居',
    pr: '是',
    req: { age: [18, 55], minDeg: DEG.bachelor, minEng: ENG.ielts65, workExp: 3, jobOffer: true },
    quota: '无固定名额',
    cost: 'NZ$4,890 起',
    difficulty: 4,
    notes: '2023 年改为 6 分制：学历、职业注册、收入三选一路径累计到 6 分。硬性要求是有新西兰的技术工作 offer（薪资达到中位数门槛）。所以实操上通常先 WHV / 工签落地，再转 SMC。',
    official: 'https://www.immigration.govt.nz/new-zealand-visas/visas/visa/skilled-migrant-category-resident-visa',
  },
  {
    id: 'jp-hsp',
    country: '日本', flag: '🇯🇵',
    name: '高度专门职 (高度人才)', nameEn: 'Highly Skilled Professional',
    type: 'skilled',
    duration: '5 年',
    pr: '70 分住满 3 年、80 分住满 1 年即可申永住',
    req: { minDeg: DEG.bachelor, jobOffer: true, workExp: 1 },
    quota: '无',
    cost: '很低',
    difficulty: 3,
    notes: '全球拿永居最快的路径之一：80 分只要 1 年。打分看学历（硕博加分多）、年收入、年龄（29 岁以下满分）、日语 N1、名校加分。缺点是需要日本雇主 offer，且年收入门槛在 300 万日元以上。',
    official: 'https://www.moj.go.jp/isa/applications/status/highly_skilled.html',
  },

  // ─────────────── 工作签证（有 offer 走） ───────────────
  {
    id: 'nl-hsm',
    country: '荷兰', flag: '🇳🇱',
    name: '高技术移民 (Kennismigrant)', nameEn: 'Highly Skilled Migrant',
    type: 'work',
    duration: '与合同同长，最长 5 年',
    pr: '连续 5 年可申永居',
    req: { minDeg: DEG.bachelor, minEng: ENG.ielts65, jobOffer: true },
    quota: '无',
    cost: '雇主承担为主',
    difficulty: 3,
    notes: '不需要劳动力市场测试，只看工资门槛（30 岁以上/以下两档，找工作年转换有大幅优惠价）。还有 30% 税收优惠。荷兰科技公司英语办公普遍，是欧洲对中国 IT 从业者最友好的落点之一。',
    official: 'https://ind.nl/en/residence-permits/work/highly-skilled-migrant',
  },
  {
    id: 'uk-skilled',
    country: '英国', flag: '🇬🇧',
    name: '技术工签 (Skilled Worker)', nameEn: 'Skilled Worker visa',
    type: 'work',
    duration: '最长 5 年，可续',
    pr: '住满 5 年可申 ILR 永居',
    req: { minDeg: DEG.bachelor, minEng: ENG.ielts55, jobOffer: true },
    quota: '无总量限制',
    cost: '签证费 + IHS，5 年下来个人成本常超 £10,000',
    difficulty: 3,
    notes: '必须有持牌担保雇主（Sponsor Licence）的 offer，且薪资达到门槛（近年门槛持续上调，且政策仍在收紧中，务必查最新数字）。担保雇主名单是公开的，找工作时按名单投更高效。',
    official: 'https://www.gov.uk/skilled-worker-visa',
  },
  {
    id: 'uk-globaltalent',
    country: '英国', flag: '🇬🇧',
    name: '全球人才签证', nameEn: 'Global Talent visa',
    type: 'talent',
    duration: '最长 5 年',
    pr: '杰出人才 3 年、潜力人才 5 年可申永居',
    req: { minDeg: DEG.bachelor, minEng: ENG.ielts55, skills: ['tech', 'science', 'arts', 'engineering'] },
    quota: '无',
    cost: '背书费 £561 + 签证费 £205',
    difficulty: 4,
    notes: '不需要雇主，先拿行业背书机构（Tech Nation 类、UKRI、艺术委员会等）的认可。适合有开源项目、论文、专利、作品集、创业经历的人。硬通货是「可验证的公开成果」，不是学历。',
    official: 'https://www.gov.uk/global-talent',
  },
  {
    id: 'sg-ep',
    country: '新加坡', flag: '🇸🇬',
    name: '就业准证 (EP)', nameEn: 'Employment Pass',
    type: 'work',
    duration: '2 年（首次），可续',
    pr: '通常工作 2–3 年后可申 PR',
    req: { minDeg: DEG.bachelor, minEng: ENG.ielts55, jobOffer: true },
    quota: '无',
    cost: '雇主承担',
    difficulty: 3,
    notes: '除薪资门槛外还要过 COMPASS 积分（学历、薪资、公司国籍多样性、本地雇佣占比等）。名校毕业生在 COMPASS 里有明确加分。中文环境友好、税低、离国内近，是很多人的首选。',
    official: 'https://www.mom.gov.sg/passes-and-permits/employment-pass',
  },
  {
    id: 'sg-onepass',
    country: '新加坡', flag: '🇸🇬',
    name: '顶级专才准证 (ONE Pass)', nameEn: 'Overseas Networks & Expertise Pass',
    type: 'talent',
    duration: '5 年，可续',
    pr: '可申 PR',
    req: { minDeg: DEG.bachelor, minEng: ENG.ielts65, workExp: 5 },
    quota: '无',
    cost: 'S$105',
    difficulty: 5,
    notes: '要求过去一年月薪 S$30,000 以上（约 17 万人民币/月），或在艺术体育科研等领域有杰出成就。门槛极高但自由度最大：不绑雇主，可同时在多家公司任职。',
    official: 'https://www.mom.gov.sg/passes-and-permits/overseas-networks-expertise-pass',
  },
  {
    id: 'ie-critical',
    country: '爱尔兰', flag: '🇮🇪',
    name: '关键技能工签', nameEn: 'Critical Skills Employment Permit',
    type: 'work',
    duration: '2 年，之后可申无限制居留',
    pr: '5 年可申永居，之后可入籍（承认双国籍）',
    req: { minDeg: DEG.bachelor, minEng: ENG.ielts65, jobOffer: true },
    quota: '无',
    cost: '€1,000 许可费',
    difficulty: 3,
    notes: '英语国家 + 欧盟成员国，双重优势。关键技能职业清单（IT、工程、医护、金融）薪资门槛较低，清单外职业门槛高得多。2 年后可获得不绑雇主的居留许可，自由度高。',
    official: 'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/permit-types/critical-skills-employment-permit/',
  },
  {
    id: 'us-h1b',
    country: '美国', flag: '🇺🇸',
    name: 'H-1B 工作签证', nameEn: 'H-1B',
    type: 'work',
    duration: '3 年，可续至 6 年',
    pr: '需雇主 sponsor 绿卡，中国大陆出生排期数年',
    req: { minDeg: DEG.bachelor, minEng: ENG.ielts65, jobOffer: true },
    quota: '每年 8.5 万个名额，抽签制，中签率常年 20–30%',
    cost: '雇主承担为主',
    difficulty: 5,
    notes: '最大的不确定性是抽签。实操主流路径是先 F-1 留学 → OPT（STEM 专业可到 36 个月）→ 期间抽 H-1B，抽三年不中就得走人。直接从境外抽签几乎没有雇主愿意配合。',
    official: 'https://www.uscis.gov/working-in-the-united-states/h-1b-specialty-occupations',
  },
  {
    id: 'us-niw',
    country: '美国', flag: '🇺🇸',
    name: 'EB-2 NIW 国家利益豁免', nameEn: 'EB-2 National Interest Waiver',
    type: 'talent',
    duration: '直接申请绿卡',
    pr: '是，但中国大陆出生有排期（数年）',
    req: { minDeg: DEG.master, minEng: ENG.ielts65, skills: ['science', 'tech', 'engineering', 'healthcare'] },
    quota: '受 EB-2 排期限制',
    cost: '律师费 US$8,000–15,000 + 官费',
    difficulty: 4,
    notes: '不需要雇主、不需要 offer，自己给自己申请绿卡。核心是证明你的工作「对美国有国家利益」：论文、引用、专利、审稿经历、媒体报道、推荐信。学术和科研背景的人最吃这条路。缺点是排期长。',
    official: 'https://www.uscis.gov/working-in-the-united-states/permanent-workers/employment-based-immigration-second-preference-eb-2',
  },
  {
    id: 'us-o1',
    country: '美国', flag: '🇺🇸',
    name: 'O-1 杰出人才签证', nameEn: 'O-1A / O-1B',
    type: 'talent',
    duration: '3 年，可无限续',
    pr: '常作为 EB-1A 的前置步骤',
    req: { minDeg: DEG.bachelor, minEng: ENG.ielts65, workExp: 3 },
    quota: '无名额限制，不用抽签',
    cost: '律师费 US$10,000–20,000',
    difficulty: 5,
    notes: '需要满足 8 条标准中的至少 3 条（获奖、媒体报道、评审他人工作、原创贡献、高薪、专业组织成员等）。需要一个 sponsor（可以是自己的公司或经纪机构）。近年成为科技圈绕开 H-1B 抽签的主流选择。',
    official: 'https://www.uscis.gov/working-in-the-united-states/temporary-workers/o-1-visa-individuals-with-extraordinary-ability-or-achievement',
  },

  // ─────────────── 留学转移民 ───────────────
  {
    id: 'uk-graduate',
    country: '英国', flag: '🇬🇧',
    name: '毕业生签证 (PSW)', nameEn: 'Graduate Route',
    type: 'study',
    duration: '2 年（博士 3 年）',
    pr: '需转 Skilled Worker 累计 5 年',
    req: { minDeg: DEG.bachelor, minEng: ENG.ielts65, studyIn: 'uk' },
    quota: '无',
    cost: '签证费 £880 + IHS',
    difficulty: 2,
    notes: '前提是先在英国本土读完学位。不需要 offer 就能留 2 年找工作。注意：该政策近年一直在被审议收紧（时长和资格都可能变），申请前务必确认当年规则。',
    official: 'https://www.gov.uk/graduate-visa',
  },
  {
    id: 'hk-iang',
    country: '中国香港', flag: '🇭🇰',
    name: 'IANG 毕业生留港', nameEn: 'IANG',
    type: 'study',
    duration: '首次 24 个月，无条件逗留',
    pr: '连续 7 年可申永居',
    req: { minDeg: DEG.bachelor, studyIn: 'hk' },
    quota: '无',
    cost: '极低',
    difficulty: 1,
    notes: '香港本地院校毕业（含一年制授课型硕士）即可无条件留港 2 年，不需要 offer。一年制硕士 + IANG 是性价比很高的「花一年时间换 7 年永居倒计时」方案，学费约 15–30 万港币。',
    official: 'https://www.immd.gov.hk/eng/services/visas/IANG.html',
  },
  {
    id: 'de-study',
    country: '德国', flag: '🇩🇪',
    name: '留学 + 毕业找工签', nameEn: 'Student visa → Job seeker',
    type: 'study',
    duration: '学制 + 18 个月找工作期',
    pr: '工作满 21–33 个月可申永居',
    req: { minDeg: DEG.bachelor, minEng: ENG.ielts55, fundsUSD: 13000 },
    quota: '无',
    cost: '公立大学基本免学费，只需注册费 + 封锁账户约 €12,000/年',
    difficulty: 3,
    notes: '欧洲成本最低的留学转移民路线之一：公立免学费。英授硕士项目越来越多，但找工作时德语仍是重要门槛（尤其非 IT 行业）。毕业后 18 个月找工作期很宽松。',
    official: 'https://www.study-in-germany.de/',
  },

  // ─────────────── 数字游民 / 远程工作 ───────────────
  {
    id: 'pt-d8',
    country: '葡萄牙', flag: '🇵🇹',
    name: 'D8 数字游民签证', nameEn: 'Digital Nomad Visa (D8)',
    type: 'nomad',
    duration: '首次 2 年，可续 3 年',
    pr: '合法居住 5 年可申永居并可入籍',
    req: { minEng: ENG.daily, fundsUSD: 3800 },
    quota: '无',
    cost: '申请费约 €180 + 住址证明 + 医疗保险',
    difficulty: 3,
    notes: '欧洲数字游民签里最有价值的一条：因为它通往葡萄牙国籍（5 年，且实际居住要求宽松）。要求境外远程收入达到葡萄牙最低工资约 4 倍的月收入水平。需要提供劳动合同或客户合同证明。',
    official: 'https://www.vistos.mne.gov.pt/en/national-visas/necessary-documentation/remote-work-visa',
  },
  {
    id: 'es-dnv',
    country: '西班牙', flag: '🇪🇸',
    name: '数字游民签证', nameEn: 'Digital Nomad Visa',
    type: 'nomad',
    duration: '首次 1–3 年，可续',
    pr: '5 年可申长期居留，10 年可入籍',
    req: { minEng: ENG.daily, fundsUSD: 3200, workExp: 3 },
    quota: '无',
    cost: '申请费低，需医保 + 无犯罪记录公证',
    difficulty: 3,
    notes: '要求为境外公司远程工作（该公司需成立满 1 年，且给你的合同满 3 个月），本地客户收入不得超过 20%。有 Beckham 法案税收优惠（前 4 年 24% 固定税率）。入籍要 10 年且需放弃原国籍。',
    official: 'https://www.exteriores.gob.es/',
  },
  {
    id: 'th-dtv',
    country: '泰国', flag: '🇹🇭',
    name: 'DTV 目的地泰国签证', nameEn: 'Destination Thailand Visa',
    type: 'nomad',
    duration: '5 年多次往返，每次停留 180 天',
    pr: '不通往永居',
    req: { fundsUSD: 14000 },
    quota: '无',
    cost: '签证费约 10,000 泰铢',
    difficulty: 2,
    notes: '2024 年新政，门槛相当低：50 万泰铢存款（约 1.4 万美元）+ 远程工作证明或参加泰国活动（泰拳、烹饪课等）的证明。5 年有效期、生活成本低，是亚洲最舒服的落脚点之一。但纯属长期居留，没有身份升级路径。',
    official: 'https://www.thaievisa.go.th/',
  },
  {
    id: 'my-derantau',
    country: '马来西亚', flag: '🇲🇾',
    name: 'DE Rantau 游民通行证', nameEn: 'DE Rantau Nomad Pass',
    type: 'nomad',
    duration: '3–12 个月，可续 12 个月',
    pr: '不通往永居（另有 MM2H 长居计划）',
    req: { fundsUSD: 24000, skills: ['tech', 'business', 'arts'] },
    quota: '无',
    cost: 'RM1,000 申请费',
    difficulty: 2,
    notes: '年收入 24,000 美元即可，主要面向 IT / 数字营销 / 内容创作等远程职业。中文环境友好、生活成本低、时区和国内一致，适合过渡。可带配偶子女。',
    official: 'https://mdec.my/derantau',
  },

  // ─────────────── 创业 / 投资 ───────────────
  {
    id: 'ca-suv',
    country: '加拿大', flag: '🇨🇦',
    name: '创业签证 (SUV)', nameEn: 'Start-up Visa',
    type: 'invest',
    duration: '直接申请永居',
    pr: '是',
    req: { minEng: ENG.ielts55, fundsUSD: 20000 },
    quota: '近年收紧，处理周期被拉长',
    cost: '孵化器/天使投资背书费用常达数万加元，总成本 CAD$100,000+',
    difficulty: 4,
    notes: '需要拿到加拿大指定机构（孵化器、天使投资、风投）的支持信。最多 5 个创始人共享一封支持信。近年因申请量暴增，官方设置了年度处理上限，等待期显著变长。市面上大量「包过」中介风险很高。',
    official: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/start-visa.html',
  },
  {
    id: 'uk-innovator',
    country: '英国', flag: '🇬🇧',
    name: '创新创始人签证', nameEn: 'Innovator Founder visa',
    type: 'invest',
    duration: '3 年，可续',
    pr: '3 年可申永居（比工签快 2 年）',
    req: { minEng: ENG.ielts55, fundsUSD: 30000 },
    quota: '无',
    cost: '背书费 + 签证费 + 实际启动资金',
    difficulty: 4,
    notes: '2023 年取消了 £50,000 最低投资额硬性要求，改为由背书机构评估商业计划的创新性、可行性、可扩展性。3 年拿永居是英国最快的路径之一。难点在于通过背书机构的审查。',
    official: 'https://www.gov.uk/innovator-founder-visa',
  },
  {
    id: 'ae-golden',
    country: '阿联酋', flag: '🇦🇪',
    name: '黄金签证', nameEn: 'UAE Golden Visa',
    type: 'invest',
    duration: '5–10 年，可续',
    pr: '长期居留，但不通往国籍',
    req: { fundsUSD: 545000 },
    quota: '无',
    cost: '房产投资 200 万迪拉姆起，或走人才类别',
    difficulty: 3,
    notes: '零个人所得税是最大卖点。除投资路径外，还有人才类别（科学家、医生、程序员、创作者等）可以低成本申请，程序员类别对有一定履历的 IT 从业者比较友好。不通往国籍，是纯粹的「税务 + 生活」选择。',
    official: 'https://u.ae/en/information-and-services/visa-and-emirates-id/residence-visas/golden-visa',
  },
];

/** 简单的一致性自检，帮助贡献者在浏览器控制台里发现数据问题。 */
function validatePathways() {
  const seen = new Set();
  const problems = [];
  for (const p of PATHWAYS) {
    if (seen.has(p.id)) problems.push(`重复 id: ${p.id}`);
    seen.add(p.id);
    for (const f of ['country', 'name', 'type', 'duration', 'notes', 'official']) {
      if (!p[f]) problems.push(`${p.id} 缺少字段 ${f}`);
    }
    if (!TYPE_LABEL[p.type]) problems.push(`${p.id} 的 type "${p.type}" 未定义`);
  }
  return problems;
}
