/**
 * 润学导航 · 路径数据集
 *
 * 字段说明见 CONTRIBUTING.md。
 * 所有数据仅供初筛参考，政策随时变动，务必以 official 链接的官方页面为准。
 *
 * 等级编码（用于比较）：
 *   学历 DEG:  0 无 / 1 高中 / 2 大专 / 3 本科 / 4 硕士 / 5 博士
 *   英语 ENG:  0 几乎不会 / 1 日常交流 / 2 雅思5.5 / 3 雅思6.5 / 4 接近母语
 *   学校 UNI:  数字 = 世界排名档位（50 / 100 / 200 / 500 / 9999 表示不限）
 */

const DEG = { none: 0, highschool: 1, college: 2, bachelor: 3, master: 4, phd: 5 };
const ENG = { none: 0, daily: 1, ielts55: 2, ielts65: 3, fluent: 4 };

const DEG_LABEL = ['无学历', '高中', '大专', '本科', '硕士', '博士'];
const ENG_LABEL = ['几乎不会', '日常交流', '雅思 5.5 / CET-6 水平', '雅思 6.5 / 工作可用', '接近母语'];

/**
 * 法语水平。单独建模是因为它能打开一批英语路径打不开的门 ——
 * 尤其是加拿大 Express Entry 的法语类别定向邀请。
 */
const FRA = { none: 0, basic: 1, mid: 2, nclc7: 3 };
const FRA_LABEL = ['不会法语', '入门 (A1–A2)', '中级 (NCLC 5–6)', 'NCLC 7+ / TEF B2 以上'];

/**
 * 其他小语种。这里只记「有没有达到能用的水平」，不分档 ——
 * 因为它们通常是某条路径的开关（有就能走，没有就走不了），
 * 不像英语法语那样每一档都对应不同的签证。
 */
const LANGS = {
  de: '德语',
  ja: '日语',
  ko: '韩语',
  es: '西班牙语',
  nordic: '北欧语言（芬兰语/挪威语/瑞典语等）',
};

/** 学位就读地 —— 部分路径要求学位必须在当地取得（如香港 IANG、英国 PSW）。 */
const STUDY_LOC = {
  cn: '中国大陆',
  hk: '中国香港',
  // 亚太
  jp: '日本', kr: '韩国', sg: '新加坡', au: '澳大利亚', nz: '新西兰',
  // 英语区
  uk: '英国', ie: '爱尔兰', us: '美国', ca: '加拿大',
  // 欧洲逐国 —— 毕业后找工作签几乎都只认本国学位，
  // 笼统的「欧洲」会让德国学位错误匹配上瑞典、挪威的毕业签
  de: '德国', fr: '法国', nl: '荷兰', it: '意大利', es: '西班牙', pt: '葡萄牙',
  se: '瑞典', no: '挪威', dk: '丹麦', fi: '芬兰', be: '比利时', at: '奥地利', pl: '波兰',
  eu: '其他欧洲国家',
  other: '其他国家 / 地区',
};

const SKILLS = {
  tech: 'IT / 软件开发',
  engineering: '工程 / 制造',
  healthcare: '医护 / 生物医药',
  finance: '金融 / 会计',
  science: '科研 / 学术',
  education: '教育 / 培训',
  trades: '技工（厨师/电焊/美发/建筑等）',
  business: '管理 / 市场 / 运营',
  arts: '设计 / 媒体 / 创作',
  none: '暂无明确专业技能',
};

const GOALS = {
  fast: '尽快先出去，落脚再说',
  pr: '奔着永居 / 护照去',
  cheap: '预算有限，越便宜越好',
  family: '要带配偶 / 孩子',
  study: '接受再读一个学位',
  remote: '有远程工作 / 想数字游民',
  business: '有创业或投资打算',
};

/**
 * 发达国家 / 地区，用于结果筛选。
 * 采用 IMF「先进经济体」(Advanced Economies) 口径。
 *
 * 注意几个容易有争议的：
 *   阿联酋 —— 人均收入很高，但 IMF 仍归类为新兴与发展中经济体，故不在此列。
 *   中国香港、新加坡 —— 属于先进经济体。
 */
const DEVELOPED = new Set([
  '美国', '加拿大', '英国', '爱尔兰', '德国', '法国', '荷兰', '葡萄牙', '西班牙',
  '日本', '韩国', '新加坡', '中国香港', '澳大利亚', '新西兰',
  '芬兰', '挪威', '斯洛文尼亚', '克罗地亚', '意大利', '丹麦', '瑞典', '比利时', '奥地利',
  // 「欧盟」是跨国路径，按发达经济体处理；波兰、厄瓜多尔按 IMF 口径属新兴经济体
  '欧盟',
]);

/** 地区归属。格鲁吉亚地跨欧亚，按润学语境归入「中东 · 其他」。 */
const REGION_LABEL = {
  asia: '亚洲',
  eu: '欧洲',
  na: '北美',
  oc: '大洋洲',
  latam: '拉美',
  other: '中东 · 其他',
};

const REGION_OF = {
  日本: 'asia', 中国香港: 'asia', 韩国: 'asia', 新加坡: 'asia', 泰国: 'asia', 马来西亚: 'asia',
  英国: 'eu', 爱尔兰: 'eu', 荷兰: 'eu', 德国: 'eu', 法国: 'eu', 葡萄牙: 'eu', 西班牙: 'eu',
  意大利: 'eu', 波兰: 'eu', 芬兰: 'eu', 瑞典: 'eu', 挪威: 'eu', 丹麦: 'eu',
  比利时: 'eu', 奥地利: 'eu', 斯洛文尼亚: 'eu', 克罗地亚: 'eu', 欧盟: 'eu',
  美国: 'na', 加拿大: 'na',
  澳大利亚: 'oc', 新西兰: 'oc',
  厄瓜多尔: 'latam', 乌拉圭: 'latam',
  阿联酋: 'other', 格鲁吉亚: 'other',
};

/**
 * 排除条件（「我不想…」）。
 * test 返回 true = 这条路径命中了该排除项，勾选后会被筛掉。
 * 只用已有字段判断，不额外标注数据，避免两处数据不同步。
 */
const EXCLUDES = {
  noStudy: {
    label: '不想再读书',
    hint: '连同「必须先在当地读完学位」的找工作签一起筛掉',
    // 很多「毕业生找工作签」类型上不叫留学，但前提是先在当地念完书。
    // 反过来，已经持有当地学位的人不需要再读，那些路径要保留。
    test: (p, profile) => {
      const needsLocal = !!p.req?.studyIn;
      if (needsLocal) return p.req.studyIn !== profile?.studyLoc;
      return ['study', 'vocational'].includes(p.type);
    },
  },
  noMoney: {
    label: '不想花大钱',
    hint: '筛掉需要投入 $20,000 以上的（资金证明或实际花费，取高者）',
    // 资金证明只是门槛之一，律师费、背书费这类实际支出写在 cost 文本里
    // 程序读不到，所以对这类路径单独标注 costUSD 作为估算。
    test: (p) => Math.max(p.req?.fundsUSD || 0, p.costUSD || 0) >= 20000,
  },
  noLang: {
    label: '不想考语言',
    hint: '筛掉需要你再去考、再去学的语言门槛',
    // 只筛掉「比你现有水平更高」的要求 —— 已经达标的不算负担
    test: (p, profile) => {
      const needEng = (p.req?.minEng ?? 0) > (profile?.english ?? 0);
      const needFra = (p.req?.minFrench ?? 0) > (profile?.french ?? 0);
      const needOther = !!p.req?.otherLang && !(profile?.langs || []).includes(p.req.otherLang.code);
      return needEng || needFra || needOther;
    },
  },
  noOffer: {
    label: '拿不到海外 offer',
    test: (p) => !!p.req?.jobOffer,
  },
  noInvest: {
    label: '不想投资创业',
    test: (p) => p.type === 'invest',
  },
};

const TYPE_LABEL = {
  workholiday: '打工度假',
  jobseek: '毕业生找工作签',
  talent: '人才引进',
  skilled: '技术移民',
  work: '工作签证',
  study: '留学转移民',
  vocational: '职业教育 / 学徒',
  nomad: '数字游民',
  invest: '创业 / 投资',
  soft: '软着陆 / 落脚点',
};

/**
 * req 中所有字段都是「门槛」，留空 = 无此要求。
 *   age:[min,max]  minDeg  uniRank  gradWithin(年)  minEng
 *   workExp(年)  jobOffer(bool)  fundsUSD  skills[](满足其一即可)
 *   studyIn: STUDY_LOC 的 key，表示学位必须在该地取得
 */
const PATHWAYS = [
  // ─────────────── 打工度假 / 快速出去 ───────────────
  {
    id: 'nz-whv',
    country: '新西兰', flag: '🇳🇿',
    name: '打工度假签证 (WHV)', nameEn: 'Working Holiday Visa',
    type: 'workholiday',
    duration: '12 个月',
    pr: '本身不通往永居，但可在境内转学签或技术工签',
    req: { age: [18, 30], minDeg: DEG.highschool, minEng: ENG.ielts55, fundsUSD: 3000 },
    quota: '中国大陆每年 1000 个名额，开放即秒光，需要拼手速',
    cost: '签证费约 NZ$470 + 机票 + 押金资金证明',
    difficulty: 3,
    notes: '门槛最低的一条「先出去」路线。要求雅思 5.5（或同等），需体检。名额是最大瓶颈，通常提前几个月蹲开放时间。',
    official: 'https://www.immigration.govt.nz/new-zealand-visas/visas/visa/china-special-work-visa',
  },
  {
    id: 'au-whv462',
    country: '澳大利亚', flag: '🇦🇺',
    name: '打工度假签证 (462)', nameEn: 'Work and Holiday visa (subclass 462)',
    type: 'workholiday',
    duration: '12 个月，满足偏远地区工作可续签',
    pr: '不直接通往永居，但可转雇主担保 / 学签',
    req: { age: [18, 30], minDeg: DEG.college, minEng: ENG.ielts55, fundsUSD: 3500 },
    quota: '中国大陆每年 5000 个名额',
    cost: '签证费约 AUD$680 + 机票 + 资金证明约 AUD$5,000',
    difficulty: 3,
    notes: '中国大陆护照走的是 462 类别（不是 417）。需要大专以上学历或本科在读满 2 年、英语能力证明、中文水平证明。农场 / 服务业工作机会多。',
    official: 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/work-holiday-462',
  },
  {
    id: 'sg-whp',
    country: '新加坡', flag: '🇸🇬',
    name: '打工度假通行证 (WHP)', nameEn: 'Work Holiday Pass',
    type: 'workholiday',
    duration: '6 个月，不可续',
    pr: '不通往永居，属于短期体验',
    req: { age: [18, 25], minDeg: DEG.bachelor, uniRank: 200, minEng: ENG.daily },
    quota: '2000 个在效名额',
    cost: 'S$180 申请费',
    difficulty: 2,
    notes: '只对指定国家/地区院校的在读生或毕业生开放，年龄卡得很死（18–25）。时间短，适合当作了解新加坡就业市场的跳板，期间可无缝面试转 EP。',
    official: 'https://www.mom.gov.sg/passes-and-permits/work-holiday-programme',
  },
  {
    id: 'ge-visafree',
    country: '格鲁吉亚', flag: '🇬🇪',
    name: '免签停留 1 年', nameEn: 'Visa-free stay',
    type: 'soft',
    duration: '365 天，出境再入境可刷新',
    pr: '需另行申请居留，永居路径慢',
    req: {},
    quota: '无',
    cost: '只要机票，生活成本约 US$700–1200/月',
    difficulty: 1,
    notes: '中国护照免签停留一年，几乎零门槛的「先落地」选项。适合远程工作者和过渡期缓冲。注意：这是停留权不是移民路径，长期需转居留许可。',
    official: 'https://geoconsul.gov.ge/en/visaInformation',
  },

  // ─────────────── 毕业生找工作签（QS 名校向） ───────────────
  {
    id: 'uk-hpi',
    country: '英国', flag: '🇬🇧',
    name: '高潜力人才签证 (HPI)', nameEn: 'High Potential Individual visa',
    type: 'jobseek',
    duration: '2 年（博士 3 年）',
    pr: '需在期内转 Skilled Worker，累计 5 年可申永居',
    req: { minDeg: DEG.bachelor, uniRank: 50, gradWithin: 5, minEng: ENG.ielts55, fundsUSD: 1800 },
    quota: '无名额限制',
    cost: '签证费 £822 + 医疗附加费 IHS 每年 £1,035',
    difficulty: 2,
    notes: '不需要雇主担保、不需要工作 offer，纯凭学校血统。认可名单是英国官方每年发布的 Global Universities List（大致对应世界前 50），必须是毕业当年名单上的学校。',
    official: 'https://www.gov.uk/high-potential-individual-visa',
  },
  {
    id: 'jp-jfind',
    country: '日本', flag: '🇯🇵',
    name: 'J-Find 未来创造人才', nameEn: 'J-Find / Future Creation Individual',
    type: 'jobseek',
    duration: '最长 2 年（先给 1 年，可续）',
    pr: '可转工签或高度人才，高度人才最快 1 年拿永居',
    req: { minDeg: DEG.bachelor, uniRank: 100, gradWithin: 5, fundsUSD: 1400 },
    quota: '无名额限制',
    cost: '签证费很低（数千日元），需 20 万日元以上存款证明',
    difficulty: 2,
    notes: '不要求日语、不要求 offer。名校认定看三大排名（QS / THE / 上海交大）中至少两个的前 100。期间可以打工，也可以搞创业准备。日本生活成本相对低是加分项。',
    official: 'https://www.moj.go.jp/isa/publications/materials/nyuukokukanri07_00212.html',
  },
  {
    id: 'nl-orientation',
    country: '荷兰', flag: '🇳🇱',
    name: '找工作年签证 (Zoekjaar)', nameEn: 'Orientation Year / Zoekjaar',
    type: 'jobseek',
    duration: '12 个月',
    pr: '转高技术移民后连续 5 年可申永居',
    req: { minDeg: DEG.master, uniRank: 200, gradWithin: 3, minEng: ENG.ielts65 },
    quota: '无名额限制',
    cost: '约 €228 申请费',
    difficulty: 2,
    notes: '毕业 3 年内的世界前 200 硕博可申。最大好处：在这一年内找到工作转高技术移民时，工资门槛按「毕业生优惠价」算（远低于常规标准），转换非常顺滑。荷兰英语环境好。',
    official: 'https://ind.nl/en/residence-permits/work/orientation-year-highly-educated-persons',
  },
  {
    id: 'hk-ttps',
    country: '中国香港', flag: '🇭🇰',
    name: '高端人才通行证 (高才通)', nameEn: 'Top Talent Pass Scheme',
    type: 'talent',
    duration: '首次 24–36 个月，有工作可续',
    pr: '连续通常居住 7 年可申永久居民',
    req: { minDeg: DEG.bachelor, uniRank: 100 },
    quota: 'C 类设年度配额，先到先得；A/B 类不设限',
    cost: '签证费约 HK$600，几乎零成本',
    difficulty: 1,
    notes: '润学性价比之王，不需要 offer、不需要英语考试、不用离开中文环境。三类：A 类看收入（申请前一年年收入 250 万港币以上，获批 36 个月）；B 类是合资格大学学位 + 过去 5 年内有 3 年工作经验（24 个月）；C 类是毕业 5 年内但经验不足 3 年（24 个月，设年度配额、先到先得）。注意「合资格大学名单」不等于单一的 QS100——它是四个世界排名榜单前 100 的合并名单，另外还纳入了若干酒店管理和设计类专门院校，务必到入境处官网核对当年名单。',
    official: 'https://www.immd.gov.hk/eng/services/visas/TTPS.html',
  },
  {
    id: 'hk-qmas',
    country: '中国香港', flag: '🇭🇰',
    name: '优秀人才入境计划 (优才)', nameEn: 'QMAS',
    type: 'talent',
    duration: '首次通常 24–36 个月',
    pr: '住满 7 年可申永久居民',
    req: { age: [18, 50], minDeg: DEG.bachelor, minEng: ENG.daily },
    quota: '配额安排以入境处最新公告为准',
    cost: '申请费低，但需要材料准备成本',
    difficulty: 3,
    notes: '仍然是计分制（网上「已取消计分制」的说法不实，以入境处页面为准）。两条路二选一：综合计分制看 12 项评核准则，成就计分制看 2 项，达到分数线后由入境处按整体情况择优甄选——**过线不等于获批**。不要求名校出身，双非本科 + 漂亮的工作履历也有机会，适合高才通够不着的人。近年明显向科创、金融、生物医药等重点产业倾斜。',
    official: 'https://www.immd.gov.hk/eng/services/visas/quality_migrant_admission_scheme.html',
  },
  {
    id: 'kr-d10',
    country: '韩国', flag: '🇰🇷',
    name: 'D-10 求职签证', nameEn: 'D-10 Job Seeking Visa',
    type: 'jobseek',
    duration: '6 个月一次，最长累计 2 年',
    pr: '需转 E-7 工签，再走积分制居留',
    req: { minDeg: DEG.bachelor, fundsUSD: 3000 },
    quota: '无',
    cost: '申请费低',
    difficulty: 3,
    notes: '积分制（学历、年龄、韩语 TOPIK、工作经验等）。韩国本地毕业生转 D-10 更容易。韩语能力对找工作影响很大，纯英语环境岗位有限。',
    official: 'https://www.visa.go.kr/',
  },
  {
    id: 'de-chancenkarte',
    country: '德国', flag: '🇩🇪',
    name: '机会卡 (Chancenkarte)', nameEn: 'Opportunity Card',
    type: 'jobseek',
    duration: '12 个月，可延长',
    pr: '转工签后 21–33 个月可申永居（视德语水平）',
    req: { minDeg: DEG.college, minEng: ENG.ielts55, fundsUSD: 14000 },
    quota: '无',
    cost: '签证费约 €75 + 资金证明约 €13,000（封锁账户）',
    difficulty: 3,
    notes: '2024 年新政，积分制（学历、工作经验、德语/英语、年龄、是否有德国经历）满 6 分即可。也接受被认可的职业资格（技工路线），不一定要本科。找工作期间每周可打工 20 小时。',
    official: 'https://www.make-it-in-germany.com/en/visa-residence/types/opportunity-card',
  },
  {
    id: 'fr-rece',
    country: '法国', flag: '🇫🇷',
    name: '毕业生找工作居留 (RECE)', nameEn: 'Recherche d\'emploi ou création d\'entreprise',
    type: 'jobseek',
    duration: '12 个月，不可续',
    pr: '需转人才护照或工签，5 年可申永居',
    req: { minDeg: DEG.master, gradWithin: 4, minEng: ENG.daily, studyIn: 'fr' },
    quota: '无',
    cost: '约 €225',
    difficulty: 3,
    notes: '主要面向法国本地院校硕士毕业生；部分情况下认可法国高校在境外的合作学位。法语能力对找工作影响很大。另有一类特殊选项：法国的 42 编程学校学费全免、不看学历、只凭入学测试录取，适合想转码又没有文凭的人，但它本身不提供签证，需另行申请学生居留。',
    official: 'https://www.service-public.fr/particuliers/vosdroits/F16922',
  },

  // ── 毕业后找工作签（需在当地取得学位）──
  {
    id: 'de-jobsearch',
    country: '德国', flag: '🇩🇪',
    name: '毕业后找工作居留', nameEn: 'Residence permit to seek employment',
    type: 'jobseek',
    duration: '18 个月',
    pr: '转工签后 21–33 个月可申永居（视德语水平）',
    req: { minDeg: DEG.bachelor, minEng: ENG.ielts55, studyIn: 'de' },
    quota: '无', cost: '约 €100', difficulty: 2,
    notes: '在德国本地读完学位后可申请，**18 个月是欧洲最长的找工作期之一**，期间可不受限制地打工。德国公立大学免学费，「免费读书 + 18 个月缓冲」的组合让它成为欧洲性价比最高的留学转移民路线。非 IT 行业德语仍是硬门槛。',
    official: 'https://www.make-it-in-germany.com/en/visa-residence/types/jobseekers',
  },
  {
    id: 'fi-jobsearch',
    country: '芬兰', flag: '🇫🇮',
    name: '毕业后求职居留', nameEn: 'Residence permit to look for work',
    type: 'jobseek',
    duration: '2 年，可分次使用',
    pr: '转工签后累计 4–5 年可申永居',
    req: { minDeg: DEG.bachelor, minEng: ENG.ielts55, studyIn: 'fi' },
    quota: '无', cost: '约 €400', difficulty: 2,
    notes: '在芬兰完成学位后可申请，**给足 2 年**且允许分次使用（毕业后 5 年内都能启用），是欧洲最宽松的找工作签之一。芬兰英语工作环境在北欧算好的，IT 与工程岗位对英语者友好。',
    official: 'https://migri.fi/en/residence-permit-to-look-for-work',
  },
  {
    id: 'se-jobsearch',
    country: '瑞典', flag: '🇸🇪',
    name: '毕业后找工作居留', nameEn: 'Residence permit to seek work',
    type: 'jobseek',
    duration: '最长 12 个月',
    pr: '工作满 4 年可申永居',
    req: { minDeg: DEG.master, minEng: ENG.ielts65, studyIn: 'se' },
    quota: '无', cost: '约 SEK 2,200', difficulty: 3,
    notes: '需在瑞典完成硕士及以上学位。瑞典工签转永居只要 4 年，比丹麦（8 年）和挪威快得多，英语普及率极高，是北欧对外国人最友好的就业市场之一。缺点是找工作期只有 12 个月，且瑞典就业市场对本地语言仍有隐性偏好。',
    official: 'https://www.migrationsverket.se/en/you-want-to-apply/work/find-a-job.html',
  },
  {
    id: 'dk-establishment',
    country: '丹麦', flag: '🇩🇰',
    name: '创业 / 求职卡', nameEn: 'Establishment Card',
    type: 'jobseek',
    duration: '2 年',
    pr: '需转工签，累计 8 年可申永居',
    req: { minDeg: DEG.master, minEng: ENG.ielts65, studyIn: 'dk' },
    quota: '无', cost: '约 DKK 2,000', difficulty: 3,
    notes: '在丹麦完成硕士或博士后可申请，**给 2 年**且期间既能打工也能创业，自由度高于多数找工作签。丹麦永居年限长（8 年）是主要劝退点，但工作生活平衡和社会福利在欧洲名列前茅。',
    official: 'https://www.nyidanmark.dk/en-GB/You-want-to-apply/Work/Establishment%20card',
  },
  {
    id: 'be-searchyear',
    country: '比利时', flag: '🇧🇪',
    name: '找工作年居留', nameEn: 'Search Year Residence Permit',
    type: 'jobseek',
    duration: '12 个月',
    pr: '转工签后 5 年可申永居',
    req: { minDeg: DEG.bachelor, minEng: ENG.ielts55, studyIn: 'be' },
    quota: '无', cost: '约 €400', difficulty: 3,
    notes: '在比利时读完学位后可申请，期间可全职工作或创业。比利时是欧盟总部所在地，国际组织和欧盟机构岗位集中，英语working环境在布鲁塞尔较普遍。注意比利时分三个语区，弗拉芒区看荷兰语、瓦隆区看法语，找工作时语言要求差别很大。',
    official: 'https://dofi.ibz.be/en',
  },
  {
    id: 'at-jobseeker',
    country: '奥地利', flag: '🇦🇹',
    name: '红白红卡 / 求职签证', nameEn: 'Red-White-Red Card / Job Seeker Visa',
    type: 'jobseek',
    duration: '毕业生 12 个月；高技能求职签 6 个月',
    pr: '持红白红卡工作满 5 年可申永居',
    req: { minDeg: DEG.bachelor, minEng: ENG.ielts55, studyIn: 'at' },
    quota: '无', cost: '约 €160', difficulty: 3,
    notes: '两条路：在奥地利毕业的可直接申请 12 个月找工作居留；境外高技能人才走积分制求职签证（学历、经验、语言、年龄计分，达标给 6 个月入境找工作）。找到工作后转红白红卡。德语是主要门槛，维也纳的国际组织岗位是英语环境的例外。',
    official: 'https://www.migration.gv.at/en/types-of-immigration/permanent-immigration/',
  },
  {
    id: 'it-attesa',
    country: '意大利', flag: '🇮🇹',
    name: '待业居留', nameEn: 'Permesso di soggiorno per attesa occupazione',
    type: 'jobseek',
    duration: '最长 12 个月',
    pr: '合法居留满 5 年可申长居卡',
    req: { minDeg: DEG.bachelor, minEng: ENG.daily, studyIn: 'it' },
    quota: '无', cost: '很低', difficulty: 2,
    notes: '在意大利毕业或工作合同结束后可转的过渡身份，期间合法居留并找工作，这段时间同样计入永居所需的 5 年。配合意大利公立大学免学费的低成本留学，是一条完整的低预算路线。意大利语是就业硬门槛。',
    official: 'https://www.portaleimmigrazione.it/',
  },
  {
    id: 'es-jobseeker',
    country: '西班牙', flag: '🇪🇸',
    name: '毕业生求职签证', nameEn: 'Job Seeker Visa for Graduates',
    type: 'jobseek',
    duration: '12 个月',
    pr: '转工签后累计 5 年可申长期居留',
    req: { minDeg: DEG.bachelor, minEng: ENG.daily, studyIn: 'es' },
    quota: '无', cost: '较低', difficulty: 2,
    notes: '在西班牙完成学业后可申请 12 个月居留找工作或创业。西班牙生活成本在西欧偏低、气候宜人，但青年失业率长期偏高，就业市场竞争激烈，西班牙语几乎是必需。入籍要 10 年且原则上需放弃原国籍。',
    official: 'https://www.inclusion.gob.es/web/migraciones/home',
  },
  {
    id: 'no-jobseeker',
    country: '挪威', flag: '🇳🇴',
    name: '技术人才求职居留', nameEn: 'Job seeker permit for skilled workers',
    type: 'jobseek',
    duration: '通常 6–12 个月',
    pr: '转工签后连续 3 年可申永居',
    req: { minDeg: DEG.bachelor, minEng: ENG.ielts65, studyIn: 'no', fundsUSD: 25000 },
    quota: '无', cost: '约 NOK 6,300', difficulty: 4,
    notes: '面向在挪威完成学业的毕业生，或已具备技术资历的境外申请人。挪威永居只要 3 年，在北欧里最快，薪资水平也最高。门槛在于必须自行证明有足够生活费，且挪威生活成本极高、职位对挪威语要求普遍偏强。',
    official: 'https://www.udi.no/en/want-to-apply/work-immigration/job-seekers/',
  },
  {
    id: 'jp-tokutei-katsudo',
    country: '日本', flag: '🇯🇵',
    name: '特定活动（毕业后找工作）', nameEn: 'Designated Activities for Job Hunting',
    type: 'jobseek',
    duration: '6 个月，可续一次共 1 年',
    pr: '转技人国或高度人才后累计计算',
    req: { minDeg: DEG.college, studyIn: 'jp' },
    quota: '无', cost: '很低', difficulty: 2,
    notes: '在日本本地院校毕业但还没找到工作时申请，可合法留下继续求职，期间允许打工。需要学校出具的推荐函，这是与 J-Find 最大的不同——J-Find 面向境外名校毕业生、不需要在日本读过书，这条则面向日本本地毕业生、不看学校排名。',
    official: 'https://www.moj.go.jp/isa/applications/status/designatedactivities.html',
  },
  {
    id: 'us-opt',
    country: '美国', flag: '🇺🇸',
    name: 'OPT 实习工作许可', nameEn: 'Optional Practical Training',
    type: 'study',
    duration: '12 个月；STEM 专业可再延 24 个月，共 36 个月',
    pr: '需在期内抽中 H-1B 或转其他身份',
    req: { minDeg: DEG.bachelor, minEng: ENG.ielts65, studyIn: 'us' },
    quota: '无名额限制', cost: '申请费数百美元', difficulty: 3,
    notes: '美国路径的实际起点：F-1 学生毕业后凭 OPT 合法工作。**专业是否属于 STEM 决定命运**——非 STEM 只有 12 个月，等于只有一次 H-1B 抽签机会；STEM 有 36 个月，可以抽三次。所以选专业时务必查清是否在官方 STEM 清单上，这一步的影响大于学校排名。',
    official: 'https://www.uscis.gov/working-in-the-united-states/students-and-exchange-visitors/optional-practical-training-opt-for-f-1-students',
  },
  {
    id: 'sg-ltvp',
    country: '新加坡', flag: '🇸🇬',
    name: '毕业生长期探访准证 (LTVP)', nameEn: 'Long Term Visit Pass for graduates',
    type: 'study',
    duration: '1 年',
    pr: '需转 EP，之后可申 PR',
    req: { minDeg: DEG.bachelor, minEng: ENG.ielts55, studyIn: 'sg' },
    quota: '无', cost: '很低', difficulty: 2,
    notes: '在新加坡本地院校毕业后可申请 1 年居留找工作。新加坡是中文环境、税低、离国内近，本地大学（NUS/NTU）毕业生在 EP 的 COMPASS 积分里有明确加分，转就业准证相对顺畅。',
    official: 'https://www.ica.gov.sg/enter-transit-depart/for-foreigners/long-term-pass',
  },

  // ─────────────── 技术移民（直接奔永居） ───────────────
  {
    id: 'ca-ee',
    country: '加拿大', flag: '🇨🇦',
    name: '快速通道 (Express Entry)', nameEn: 'Express Entry',
    type: 'skilled',
    duration: '直接给永久居民身份',
    pr: '本身就是永居，住满约 3 年可入籍',
    req: { age: [18, 45], minDeg: DEG.bachelor, minEng: ENG.ielts65, workExp: 1, skills: ['tech', 'engineering', 'healthcare', 'trades', 'science'] },
    quota: '按 CRS 分数排队捞人，分数线浮动',
    cost: 'CAD$1,525/人 + 语言考试 + 学历认证 + 资金证明约 CAD$14,000',
    difficulty: 4,
    notes: '一步到位拿枫叶卡，含金量高但竞争激烈。CRS 打分：年龄（29 岁前满分）、学历、雅思（CLB9 分数飞涨）、工作经验、法语加分（近年法语类别捞人分数极低，是重要捷径）。境内工作经验（CEC）比境外申请优势大得多。',
    official: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry.html',
  },
  {
    id: 'ca-ee-french',
    country: '加拿大', flag: '🇨🇦',
    name: 'Express Entry 法语类别定向邀请', nameEn: 'Express Entry — French-language proficiency category',
    type: 'skilled',
    duration: '直接给永久居民身份',
    pr: '本身就是永居，住满约 3 年可入籍',
    req: { age: [18, 45], minDeg: DEG.bachelor, minFrench: FRA.nclc7, workExp: 1 },
    quota: '法语类别是近年定向邀请中占比最大的一类',
    cost: '与常规 EE 相同，另加 TEF/TCF 考试费约 CAD$400',
    difficulty: 3,
    notes: '被严重低估的一条路。法语四项都达到 NCLC 7（约 TEF B2）就能进入法语定向池，而法语类别的分数线常年显著低于常规轮次——同样的背景，法语能让你不必去拼那些几乎摸不到的高分。英语不是硬门槛（法语即可满足官方语言要求），有英语成绩则额外加分。代价是从零学到 B2 通常要 1–2 年。注意这条路不要求你去魁北克，魁省有自己独立的移民体系。',
    official: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry/submit-profile/rounds-invitations/category-based-selection.html',
  },
  {
    id: 'au-skilled',
    country: '澳大利亚', flag: '🇦🇺',
    name: '技术移民 189 / 190 / 491', nameEn: 'Skilled Migration',
    type: 'skilled',
    duration: '189/190 直接永居；491 为 5 年临居转永居',
    pr: '是',
    req: { age: [18, 44], minDeg: DEG.bachelor, minEng: ENG.ielts65, workExp: 3, skills: ['tech', 'engineering', 'healthcare', 'trades', 'science', 'education'] },
    quota: '按职业清单 + EOI 分数邀请',
    cost: 'AUD$4,765 起 + 职业评估 + 语言考试，总计常超 AUD$10,000',
    difficulty: 4,
    notes: '核心是职业评估：你的专业必须在 MLTSSL/STSOL 清单上并通过对应机构评估。分数 65 起步但实际邀请分常年 85+。IT、护理、工程、技工是主力职业。州担保（190）和偏远地区（491）可降分。',
    official: 'https://immi.homeaffairs.gov.au/visas/working-in-australia/skillselect',
  },
  {
    id: 'nz-smc',
    country: '新西兰', flag: '🇳🇿',
    name: '技术移民 (SMC)', nameEn: 'Skilled Migrant Category',
    type: 'skilled',
    duration: '直接永居',
    pr: '是',
    req: { age: [18, 55], minDeg: DEG.bachelor, minEng: ENG.ielts65, workExp: 3, jobOffer: true, skills: ['tech', 'engineering', 'healthcare', 'trades', 'science', 'education'] },
    quota: '无固定名额',
    cost: 'NZ$4,890 起',
    difficulty: 4,
    notes: '2023 年改为 6 分制：学历、职业注册、收入三选一路径累计到 6 分。硬性要求是有新西兰的技术工作 offer（薪资达到中位数门槛）。所以实操上通常先 WHV / 工签落地，再转 SMC。',
    official: 'https://www.immigration.govt.nz/new-zealand-visas/visas/visa/skilled-migrant-category-resident-visa',
  },
  {
    id: 'jp-gijinkoku',
    country: '日本', flag: '🇯🇵',
    name: '技术・人文知识・国际业务（技人国）', nameEn: 'Engineer / Specialist in Humanities / International Services',
    type: 'work',
    duration: '1 / 3 / 5 年，可无限续',
    pr: '连续居住 10 年可申永住；攒够高度人才分数可缩短到 1–3 年',
    req: { minDeg: DEG.college, jobOffer: true },
    quota: '无',
    cost: '很低，多由雇主办理',
    difficulty: 2,
    notes: '这是绝大多数中国人在日本工作实际持有的签证，也是我之前漏掉的一条主线。门槛比想象中低：**大专也可以**，关键是所学专业要和工作内容对得上（比如计算机专业做开发）；文科专业走「国际业务」路线也行。不要求日语等级证书，但实际找工作时 IT 岗位普遍要 N2、其他行业要求更高。没有名校要求、没有毕业年限限制，是 J-Find 之外更稳的长期路径。',
    official: 'https://www.moj.go.jp/isa/applications/status/gijinkoku.html',
  },
  {
    id: 'jp-ssw',
    country: '日本', flag: '🇯🇵',
    name: '特定技能', nameEn: 'Specified Skilled Worker',
    type: 'vocational',
    duration: '1 号最长 5 年；2 号可无限续签',
    pr: '1 号不通往永住；升到 2 号后可带家属，并可累积永住年限',
    req: { age: [18, 99], jobOffer: true, otherLang: { code: 'ja', label: '日语 N4 / JFT-Basic' }, skills: ['trades', 'healthcare', 'engineering'] },
    quota: '各行业分别设上限',
    cost: '考试费低，但中介费差异极大，务必比价',
    difficulty: 3,
    notes: '**不要求学历**，是日本对低学历人群开放的主要通道，也是回答「没文凭能不能润日」的答案。覆盖护理、餐饮、建筑、农业、造船、汽车维修等十余个缺工行业，通过「技能测试 + 日语 N4（或 JFT-Basic）」即可申请，薪资须与日本人同工同酬。关键区别：1 号最长 5 年、不能带家属；**升到 2 号才能长期留下并带家属**，所以入行前一定要确认所在行业是否开放 2 号。注意与旧的「技能实习」区分——后者争议很大，正被新制度取代。',
    official: 'https://www.moj.go.jp/isa/policies/ssw/index.html',
  },
  {
    id: 'jp-hsp',
    country: '日本', flag: '🇯🇵',
    name: '高度专门职 (高度人才)', nameEn: 'Highly Skilled Professional',
    type: 'skilled',
    duration: '5 年',
    pr: '70 分住满 3 年、80 分住满 1 年即可申永住',
    req: { minDeg: DEG.bachelor, jobOffer: true, workExp: 1 },
    quota: '无',
    cost: '很低',
    difficulty: 3,
    notes: '全球拿永居最快的路径之一：80 分只要 1 年。打分看学历（硕博加分多）、年收入、年龄（29 岁以下满分）、日语 N1、名校加分。缺点是需要日本雇主 offer，且年收入门槛在 300 万日元以上。',
    official: 'https://www.moj.go.jp/isa/applications/status/highly_skilled.html',
  },

  // ─────────────── 工作签证（有 offer 走） ───────────────
  {
    id: 'nl-hsm',
    country: '荷兰', flag: '🇳🇱',
    name: '高技术移民 (Kennismigrant)', nameEn: 'Highly Skilled Migrant',
    type: 'work',
    duration: '与合同同长，最长 5 年',
    pr: '连续 5 年可申永居',
    req: { minDeg: DEG.bachelor, minEng: ENG.ielts65, jobOffer: true },
    quota: '无',
    cost: '雇主承担为主',
    difficulty: 3,
    notes: '不需要劳动力市场测试，只看工资门槛（30 岁以上/以下两档，找工作年转换有大幅优惠价）。还有 30% 税收优惠。荷兰科技公司英语办公普遍，是欧洲对中国 IT 从业者最友好的落点之一。',
    official: 'https://ind.nl/en/residence-permits/work/highly-skilled-migrant',
  },
  {
    id: 'uk-skilled',
    country: '英国', flag: '🇬🇧',
    name: '技术工签 (Skilled Worker)', nameEn: 'Skilled Worker visa',
    type: 'work',
    duration: '最长 5 年，可续',
    pr: '住满 5 年可申 ILR 永居',
    req: { minDeg: DEG.bachelor, minEng: ENG.ielts55, jobOffer: true },
    quota: '无总量限制',
    cost: '签证费 + IHS，5 年下来个人成本常超 £10,000',
    difficulty: 3,
    notes: '必须有持牌担保雇主（Sponsor Licence）的 offer，且薪资达到门槛（近年门槛持续上调，且政策仍在收紧中，务必查最新数字）。担保雇主名单是公开的，找工作时按名单投更高效。',
    official: 'https://www.gov.uk/skilled-worker-visa',
  },
  {
    id: 'uk-globaltalent',
    country: '英国', flag: '🇬🇧',
    name: '全球人才签证', nameEn: 'Global Talent visa',
    type: 'talent',
    duration: '最长 5 年',
    pr: '杰出人才 3 年、潜力人才 5 年可申永居',
    req: { minDeg: DEG.bachelor, minEng: ENG.ielts55, skills: ['tech', 'science', 'arts', 'engineering'] },
    quota: '无',
    cost: '背书费 £561 + 签证费 £205',
    difficulty: 4,
    notes: '不需要雇主，先拿行业背书机构（Tech Nation 类、UKRI、艺术委员会等）的认可。适合有开源项目、论文、专利、作品集、创业经历的人。硬通货是「可验证的公开成果」，不是学历。',
    official: 'https://www.gov.uk/global-talent',
  },
  {
    id: 'sg-ep',
    country: '新加坡', flag: '🇸🇬',
    name: '就业准证 (EP)', nameEn: 'Employment Pass',
    type: 'work',
    duration: '2 年（首次），可续',
    pr: '通常工作 2–3 年后可申 PR',
    req: { minDeg: DEG.bachelor, minEng: ENG.ielts55, jobOffer: true },
    quota: '无',
    cost: '雇主承担',
    difficulty: 3,
    notes: '除薪资门槛外还要过 COMPASS 积分（学历、薪资、公司国籍多样性、本地雇佣占比等）。名校毕业生在 COMPASS 里有明确加分。中文环境友好、税低、离国内近，是很多人的首选。',
    official: 'https://www.mom.gov.sg/passes-and-permits/employment-pass',
  },
  {
    id: 'sg-onepass',
    country: '新加坡', flag: '🇸🇬',
    name: '顶级专才准证 (ONE Pass)', nameEn: 'Overseas Networks & Expertise Pass',
    type: 'talent',
    duration: '5 年，可续',
    pr: '可申 PR',
    req: { minDeg: DEG.bachelor, minEng: ENG.ielts65, workExp: 5 },
    quota: '无',
    cost: 'S$105',
    difficulty: 5,
    notes: '要求过去一年月薪 S$30,000 以上（约 17 万人民币/月），或在艺术体育科研等领域有杰出成就。门槛极高但自由度最大：不绑雇主，可同时在多家公司任职。',
    official: 'https://www.mom.gov.sg/passes-and-permits/overseas-networks-expertise-pass',
  },
  {
    id: 'ie-critical',
    country: '爱尔兰', flag: '🇮🇪',
    name: '关键技能工签', nameEn: 'Critical Skills Employment Permit',
    type: 'work',
    duration: '2 年，之后可申无限制居留',
    pr: '5 年可申永居，之后可入籍（承认双国籍）',
    req: { minDeg: DEG.bachelor, minEng: ENG.ielts65, jobOffer: true, skills: ['tech', 'engineering', 'healthcare', 'finance', 'science'] },
    quota: '无',
    cost: '€1,000 许可费',
    difficulty: 3,
    notes: '英语国家 + 欧盟成员国，双重优势。关键技能职业清单（IT、工程、医护、金融）薪资门槛较低，清单外职业门槛高得多。2 年后可获得不绑雇主的居留许可，自由度高。',
    official: 'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/permit-types/critical-skills-employment-permit/',
  },
  {
    id: 'us-h1b',
    country: '美国', flag: '🇺🇸',
    name: 'H-1B 工作签证', nameEn: 'H-1B',
    type: 'work',
    duration: '3 年，可续至 6 年',
    pr: '需雇主 sponsor 绿卡，中国大陆出生排期数年',
    req: { minDeg: DEG.bachelor, minEng: ENG.ielts65, jobOffer: true },
    quota: '每年 8.5 万个名额，抽签制，中签率常年 20–30%',
    cost: '雇主承担为主',
    difficulty: 5,
    notes: '最大的不确定性是抽签。实操主流路径是先 F-1 留学 → OPT（STEM 专业可到 36 个月）→ 期间抽 H-1B，抽三年不中就得走人。直接从境外抽签几乎没有雇主愿意配合。',
    official: 'https://www.uscis.gov/working-in-the-united-states/h-1b-specialty-occupations',
  },
  {
    id: 'us-niw',
    country: '美国', flag: '🇺🇸',
    name: 'EB-2 NIW 国家利益豁免', nameEn: 'EB-2 National Interest Waiver',
    type: 'talent',
    duration: '直接申请绿卡',
    pr: '是，但中国大陆出生有排期（数年）',
    req: { minDeg: DEG.master, minEng: ENG.ielts65, skills: ['science', 'tech', 'engineering', 'healthcare'] },
    quota: '受 EB-2 排期限制',
    cost: '律师费 US$8,000–15,000 + 官费',
    costUSD: 15000,
    difficulty: 4,
    notes: '不需要雇主、不需要 offer，自己给自己申请绿卡。核心是证明你的工作「对美国有国家利益」：论文、引用、专利、审稿经历、媒体报道、推荐信。学术和科研背景的人最吃这条路。缺点是排期长。',
    official: 'https://www.uscis.gov/working-in-the-united-states/permanent-workers/employment-based-immigration-second-preference-eb-2',
  },
  {
    id: 'us-o1',
    country: '美国', flag: '🇺🇸',
    name: 'O-1 杰出人才签证', nameEn: 'O-1A / O-1B',
    type: 'talent',
    duration: '3 年，可无限续',
    pr: '常作为 EB-1A 的前置步骤',
    req: { minDeg: DEG.bachelor, minEng: ENG.ielts65, workExp: 3 },
    quota: '无名额限制，不用抽签',
    cost: '律师费 US$10,000–20,000',
    costUSD: 20000,
    difficulty: 5,
    notes: '需要满足 8 条标准中的至少 3 条（获奖、媒体报道、评审他人工作、原创贡献、高薪、专业组织成员等）。需要一个 sponsor（可以是自己的公司或经纪机构）。近年成为科技圈绕开 H-1B 抽签的主流选择。',
    official: 'https://www.uscis.gov/working-in-the-united-states/temporary-workers/o-1-visa-individuals-with-extraordinary-ability-or-achievement',
  },

  // ─────────────── 留学转移民 ───────────────
  {
    id: 'uk-graduate',
    country: '英国', flag: '🇬🇧',
    name: '毕业生签证 (PSW)', nameEn: 'Graduate Route',
    type: 'study',
    duration: '2 年（博士 3 年）',
    pr: '需转 Skilled Worker 累计 5 年',
    req: { minDeg: DEG.bachelor, minEng: ENG.ielts65, studyIn: 'uk' },
    quota: '无',
    cost: '签证费 £880 + IHS',
    difficulty: 2,
    notes: '前提是先在英国本土读完学位。不需要 offer 就能留 2 年找工作。注意：该政策近年一直在被审议收紧（时长和资格都可能变），申请前务必确认当年规则。',
    official: 'https://www.gov.uk/graduate-visa',
  },
  {
    id: 'ca-pgwp',
    country: '加拿大', flag: '🇨🇦',
    name: '毕业工签 (PGWP)', nameEn: 'Post-Graduation Work Permit',
    type: 'study',
    duration: '按学制长短给 8 个月至 3 年，一生只能申请一次',
    pr: '用这段本地工作经验走 CEC 或省提名，是拿枫叶卡最主流的路',
    req: { minDeg: DEG.college, minEng: ENG.ielts55, studyIn: 'ca' },
    quota: '无',
    cost: 'CAD$255',
    difficulty: 2,
    notes: '加拿大移民体系的枢纽——绝大多数人不是从境外直接申永居，而是「留学 → PGWP → 攒本地工作经验 → CEC/省提名」。开放式工签，不绑雇主。**一生只能申请一次**，且近年收紧明显：所读专业必须在指定领域清单上，语言成绩也成了硬性要求，学院（college）项目的资格审查比大学严得多。选课前务必先确认该项目当年是否符合 PGWP 资格，这是最容易踩空的一步。',
    official: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/work/after-graduation/about.html',
  },
  {
    id: 'ca-peq',
    country: '加拿大', flag: '🇨🇦',
    name: '魁北克经验计划 (PEQ)', nameEn: 'Programme de l\'expérience québécoise',
    type: 'vocational',
    duration: '职业培训 (DEP) 约 1–2 年，之后申请魁省甄选证书',
    pr: '拿到 CSQ 后走联邦永居，整体比英语省份快',
    req: { age: [18, 99], minDeg: DEG.highschool, minFrench: FRA.nclc7, skills: ['trades', 'healthcare', 'engineering'] },
    quota: '无固定名额，但政策调整频繁',
    cost: '职业培训学费远低于大学本科',
    difficulty: 3,
    notes: '一条被低估的路：读魁北克的 **DEP 职业文凭**（相当于技校，护理、焊接、烹饪、汽修等），学制短、学费低、不要求本科学历，毕业后凭法语能力申请魁省甄选证书。核心门槛是法语达到 B2（约 NCLC 7），这也是它竞争小的原因。注意魁省有独立于联邦的移民体系，规则和名额单独调整、变动较频繁，申请前务必确认当年版本。',
    official: 'https://www.quebec.ca/en/immigration/permanent/quebec-experience-program',
  },
  {
    id: 'nz-psw',
    country: '新西兰', flag: '🇳🇿',
    name: '毕业后开放工签 (PSW)', nameEn: 'Post Study Work Visa',
    type: 'study',
    duration: '按学历层次给 1–3 年',
    pr: '用这段工作经验转技术移民 SMC',
    req: { minDeg: DEG.bachelor, minEng: ENG.ielts55, studyIn: 'nz' },
    quota: '无',
    cost: '约 NZ$700',
    difficulty: 2,
    notes: '在新西兰本地读完符合条件的学历后可申请，开放式工签不绑雇主。时长按学历层次算，本科及以上通常给 3 年。它是新西兰技术移民 SMC 的实际入口——因为 SMC 硬性要求本地技术工作 offer，而 PSW 正好给你找到那份工作的时间窗口。注意学历必须达到规定层级，低层次课程不再符合资格。',
    official: 'https://www.immigration.govt.nz/new-zealand-visas/visas/visa/post-study-work-visa',
  },
  {
    id: 'ie-graduate',
    country: '爱尔兰', flag: '🇮🇪',
    name: '毕业生计划 (Stamp 1G)', nameEn: 'Third Level Graduate Programme',
    type: 'study',
    duration: '学士 1 年，硕博 2 年',
    pr: '需转关键技能工签，累计 5 年可申永居',
    req: { minDeg: DEG.bachelor, minEng: ENG.ielts65, studyIn: 'ie' },
    quota: '无',
    cost: '约 €300',
    difficulty: 2,
    notes: '在爱尔兰本地取得学位后自动符合资格，期间可全职工作、不绑雇主、不需要雇主担保。爱尔兰同时是英语国家和欧盟成员国，且承认双重国籍，长期看是欧洲少数「英语 + 欧盟护照」兼得的选项。硕士毕业给 2 年，比英国 PSW 短，但转关键技能工签的薪资门槛在清单职业上并不高。',
    official: 'https://www.irishimmigration.ie/my-situation-has-changed-since-i-arrived-in-ireland/third-level-graduate-programme/',
  },
  {
    id: 'hk-iang',
    country: '中国香港', flag: '🇭🇰',
    name: 'IANG 毕业生留港', nameEn: 'IANG',
    type: 'study',
    duration: '首次 24 个月，无条件逗留',
    pr: '连续 7 年可申永居',
    req: { minDeg: DEG.bachelor, studyIn: 'hk' },
    quota: '无',
    cost: '极低',
    difficulty: 1,
    notes: '香港本地院校毕业（含一年制授课型硕士）即可无条件留港 2 年，不需要 offer。一年制硕士 + IANG 是性价比很高的「花一年时间换 7 年永居倒计时」方案，学费约 15–30 万港币。',
    official: 'https://www.immd.gov.hk/eng/services/visas/IANG.html',
  },
  {
    id: 'ie-language',
    country: '爱尔兰', flag: '🇮🇪',
    name: '语言学校留学 (Stamp 2)', nameEn: 'English Language Student / Stamp 2',
    type: 'study',
    duration: '每期 8 个月课程 + 假期，最多续 3 次（累计约 2 年）',
    pr: '本身不通往永居，需转工签后累计 5 年',
    req: { age: [18, 99], minDeg: DEG.highschool, fundsUSD: 9000 },
    quota: '无',
    cost: '语言课程学费约 €3,000–5,000/期，另需资金证明与医疗保险',
    difficulty: 2,
    notes: '英语国家里门槛最低的合法长期停留方式之一：不要求学历背景和雅思成绩，读语言课程即可拿 Stamp 2 居留，**每周可合法打工 20 小时**（假期 40 小时），基本能覆盖生活开销。目的是先落地、边提升英语边找机会转工签。硬性限制：语言学生身份最多累计约 2 年，到期必须转换身份或离境，不能无限续，所以要提前规划出路。务必选择官方 ILEP 认可名单上的学校，否则不发居留。',
    official: 'https://www.irishimmigration.ie/coming-to-study-in-ireland/',
  },
  {
    id: 'dk-positivelist',
    country: '丹麦', flag: '🇩🇰',
    name: '正面清单工签 / 薪资门槛计划', nameEn: 'Positive List & Pay Limit Scheme',
    type: 'work',
    duration: '与合同同长，最长 4 年，可续',
    pr: '合法居住满 8 年可申永居（满足加分条件可缩短至 4 年）',
    req: { minDeg: DEG.bachelor, minEng: ENG.ielts65, jobOffer: true, skills: ['tech', 'engineering', 'healthcare', 'science', 'finance'] },
    quota: '无',
    cost: '申请费约 DKK 6,000，雇主常承担',
    difficulty: 3,
    notes: '丹麦有两条并行的工签路子：正面清单（列出短缺职业，学历对口即可，薪资门槛较低）和薪资门槛计划（不限职业，但年薪须达到较高标准）。IT、工程、医护是清单常客。英语工作环境普及、工作生活平衡好是最大卖点，缺点是税极高、永居年限长（8 年）。必须先有丹麦雇主 offer，无法凭空申请。',
    official: 'https://www.nyidanmark.dk/en-GB/You-want-to-apply/Work',
  },
  {
    id: 'it-study',
    country: '意大利', flag: '🇮🇹',
    name: '公立大学留学', nameEn: 'Study in Italy',
    type: 'study',
    duration: '学制 2–3 年，毕业后可申请找工作居留',
    pr: '合法居留满 5 年可申长居卡（留学年限计入）',
    req: { age: [18, 99], minDeg: DEG.highschool, minEng: ENG.ielts55, fundsUSD: 7000 },
    quota: '无',
    cost: '公立大学免学费，只交注册费；家庭年收入低于约 €22,000 可再免除，€22,000–30,000 区间有大幅减免',
    difficulty: 2,
    notes: '欧洲成本最低的留学路线之一，而且**没有年龄限制**、不看本科出身（双非和 985 一视同仁），雅思 5.5 就能申。收入越低学费减免越多，另有 DSU 助学金每年发放几千欧元现金补助，对家境普通的申请人反而更友好。留学期间的居留年限计入永居的 5 年。主要麻烦在材料：所有文件都要翻译成意大利语并做海牙认证或双认证，流程繁琐、周期长，务必提前准备。',
    official: 'https://www.studiare-in-italia.it/studentistranieri/',
  },
  {
    id: 'jp-language-school',
    country: '日本', flag: '🇯🇵',
    name: '语言学校留学', nameEn: 'Japanese Language School',
    type: 'study',
    duration: '最长 2 年，之后可升学或转工签',
    pr: '连续居住 10 年可申永住；归化最短 5 年',
    req: { age: [18, 99], minDeg: DEG.highschool, fundsUSD: 28000 },
    quota: '无，全日本有 600 多所语言学校',
    cost: '学费约 3–4 万人民币/年，需约 20 万人民币的资金证明',
    difficulty: 2,
    notes: '对学历要求很宽松：满 12 年教育经历即可，**中专、技校、职高都算**，这在留学路径里很少见。入学不要求日语等级（提交 180 学时的学习证明即可），但想顺利升学或就职，实际需要 N2 左右。资金证明是主要门槛——20 万人民币需要冻结，但实际花掉的钱远低于这个数。日本起薪不高，图的是生活成本低和身份路径稳定。',
    official: 'https://www.studyinjapan.go.jp/en/',
  },
  {
    id: 'eu-erasmus',
    country: '欧盟', flag: '🇪🇺',
    name: 'Erasmus Mundus 全额奖学金', nameEn: 'Erasmus Mundus Joint Masters',
    type: 'study',
    duration: '2 年硕士，跨 2–4 个欧洲国家就读',
    pr: '毕业后需转各国工签，居留年限按所在国计',
    req: { minDeg: DEG.bachelor, minEng: ENG.ielts65 },
    quota: '各项目独立招生，竞争激烈',
    cost: '学费全免，另发每月约 €1,400 生活费及旅行补助',
    difficulty: 4,
    notes: '欧盟官方奖学金，不但免学费还发生活费，是真正意义上「倒贴钱让你留学」的项目，全奖总额可达三万欧元以上。本科毕业或大四在读即可申请。难点全在申请材料：**必须用欧盟格式的 CV**，且专业方向要与本科背景高度匹配——跨专业申请成功率很低，动机信的权重也远高于一般留学申请。适合本科背景对口、愿意花几个月认真打磨文书的人。',
    official: 'https://erasmus-plus.ec.europa.eu/opportunities/opportunities-for-individuals/students/erasmus-mundus-joint-masters-scholarships',
  },
  {
    id: 'de-study',
    country: '德国', flag: '🇩🇪',
    name: '留学 + 毕业找工签', nameEn: 'Student visa → Job seeker',
    type: 'study',
    duration: '学制 + 18 个月找工作期',
    pr: '工作满 21–33 个月可申永居',
    req: { minDeg: DEG.bachelor, minEng: ENG.ielts55, fundsUSD: 13000 },
    quota: '无',
    cost: '公立大学基本免学费，只需注册费 + 封锁账户约 €12,000/年',
    difficulty: 3,
    notes: '欧洲成本最低的留学转移民路线之一：公立免学费。英授硕士项目越来越多，但找工作时德语仍是重要门槛（尤其非 IT 行业）。毕业后 18 个月找工作期很宽松。',
    official: 'https://www.study-in-germany.de/',
  },

  // ─────────────── 职业教育（不看文凭，看手艺） ───────────────
  {
    id: 'de-ausbildung',
    country: '德国', flag: '🇩🇪',
    name: '双元制职业培训 (Ausbildung)', nameEn: 'Duale Ausbildung',
    type: 'vocational',
    duration: '2–3.5 年培训期，结业后可转工签',
    pr: '结业工作满 2 年左右可申永居（德语好可再缩短）',
    req: { jobOffer: true, minDeg: DEG.highschool, otherLang: { code: 'de', label: '德语 B1–B2' }, skills: ['trades', 'healthcare', 'engineering', 'business'] },
    quota: '无统一名额，取决于能否拿到企业培训岗位',
    cost: '免学费，且培训期间企业发工资（约每月 €1,000–1,200，逐年递增）',
    difficulty: 3,
    notes: '欧洲少数认手艺不认文凭的通道，对学历不高的人是真正的入口。初中/高中学历即可申请，护理、餐饮、机电、物流、酒店等行业常年缺人。真正的门槛是德语：几乎所有岗位要求 B1–B2，从零学到 B2 通常要 1–1.5 年。培训期边学边挣，不需要资金证明，这点和留学路线完全不同。结业后是德国认可的职业资格，可直接转工作签证。具体项目可留意企业自办的学院（如邮轮、酒店集团的双元制班），这类岗位常年招人且包食宿。',
    official: 'https://www.make-it-in-germany.com/en/study-training/training',
  },
  {
    id: 'fi-vet',
    country: '芬兰', flag: '🇫🇮',
    name: '职业教育 (VET)', nameEn: 'Vocational Education and Training',
    type: 'vocational',
    duration: '学制约 2–3 年（180 学分）',
    pr: '毕业后找到全职工作可转工签，累计居住满 4–5 年可申永居',
    req: { age: [18, 99], minDeg: DEG.highschool, minEng: ENG.ielts55, fundsUSD: 8000 },
    quota: '按项目招生，英语授课项目数量有限',
    cost: '公立职业教育免学费，但需自备生活费（约 €800–1,200/月）',
    difficulty: 3,
    notes: '免学费、入学门槛低（雅思 5.0–5.5 或多邻国 85 即可）、年龄无上限，是北欧少见的低门槛入口。学习期间每周可打工 20–30 小时，可携带家属且配偶可工作。主要难点：英语授课的项目少，需要自己盯招生周期；芬兰住房和生活成本高，免学费不等于低成本。',
    official: 'https://www.oph.fi/en/education-system/vocational-education-and-training-finland',
  },

  // ─────────────── 数字游民 / 远程工作 ───────────────
  {
    id: 'pt-d8',
    country: '葡萄牙', flag: '🇵🇹',
    name: 'D8 数字游民签证', nameEn: 'Digital Nomad Visa (D8)',
    type: 'nomad',
    duration: '首次 2 年，可续 3 年',
    pr: '合法居住约 5 年可申永居；入籍已收紧至 10 年',
    req: { minEng: ENG.daily, fundsUSD: 3800 },
    quota: '无',
    cost: '申请费约 €180 + 住址证明 + 医疗保险',
    difficulty: 3,
    notes: '⚠️ 2026 年 5 月 19 日生效的新国籍法大幅收紧：一般申请人入籍居住年限由 5 年延长至 10 年（欧盟及葡语国家国民为 7 年），且起算点从递交申请日改为居留卡签发日，另加语言与历史文化测试。2026 年 5 月 18 日前已递交的入籍申请仍按旧法处理。此前「5 年拿护照」的说法已经作废，但作为居留路径仍然有效：要求境外远程收入达到葡萄牙最低工资约 4 倍的月收入水平，需提供劳动合同或客户合同证明。',
    official: 'https://www.vistos.mne.gov.pt/en/national-visas/necessary-documentation/remote-work-visa',
  },
  {
    id: 'pt-d7',
    country: '葡萄牙', flag: '🇵🇹',
    name: 'D7 被动收入签证', nameEn: 'D7 Passive Income Visa',
    type: 'nomad',
    duration: '首次 2 年，可续 3 年',
    pr: '合法居住约 5 年可申永居；入籍已收紧至 10 年',
    req: { age: [18, 99], minEng: ENG.daily, fundsUSD: 1200 },
    quota: '无',
    cost: '申请费低，需当地住址证明与医疗保险',
    difficulty: 3,
    notes: '和 D8 数字游民签的区别在收入来源：D7 认的是**被动或稳定收入**（房租、养老金、分红、存款利息），门槛按葡萄牙最低工资计，远低于 D7 之外的多数欧洲居留签，对有房租或理财收入的人非常友好。⚠️ 但网上流传的「每月 700 欧 + 20 万人民币存款五年入籍」已经过时两处：最低工资标准逐年上调，且 2026 年 5 月新国籍法已把入籍年限从 5 年改为 10 年。作为居留路径依然成立，作为「快速拿欧盟护照」的方案已经不成立。另需注意居住天数要求。',
    official: 'https://www.vistos.mne.gov.pt/en/national-visas/general-information/types-of-visa',
  },
  {
    id: 'es-dnv',
    country: '西班牙', flag: '🇪🇸',
    name: '数字游民签证', nameEn: 'Digital Nomad Visa',
    type: 'nomad',
    duration: '首次 1–3 年，可续',
    pr: '5 年可申长期居留，10 年可入籍',
    req: { minEng: ENG.daily, fundsUSD: 3200, workExp: 3 },
    quota: '无',
    cost: '申请费低，需医保 + 无犯罪记录公证',
    difficulty: 3,
    notes: '要求为境外公司远程工作（该公司需成立满 1 年，且给你的合同满 3 个月），本地客户收入不得超过 20%。有 Beckham 法案税收优惠（前 4 年 24% 固定税率）。入籍要 10 年且需放弃原国籍。',
    official: 'https://www.exteriores.gob.es/',
  },
  {
    id: 'th-dtv',
    country: '泰国', flag: '🇹🇭',
    name: 'DTV 目的地泰国签证', nameEn: 'Destination Thailand Visa',
    type: 'nomad',
    duration: '5 年多次往返，每次停留 180 天',
    pr: '不通往永居',
    req: { fundsUSD: 14000 },
    quota: '无',
    cost: '签证费约 10,000 泰铢',
    difficulty: 2,
    notes: '2024 年新政，门槛相当低：50 万泰铢存款（约 1.4 万美元）+ 远程工作证明或参加泰国活动（泰拳、烹饪课等）的证明。5 年有效期、生活成本低，是亚洲最舒服的落脚点之一。但纯属长期居留，没有身份升级路径。',
    official: 'https://www.thaievisa.go.th/',
  },
  {
    id: 'my-derantau',
    country: '马来西亚', flag: '🇲🇾',
    name: 'DE Rantau 游民通行证', nameEn: 'DE Rantau Nomad Pass',
    type: 'nomad',
    duration: '3–12 个月，可续 12 个月',
    pr: '不通往永居（另有 MM2H 长居计划）',
    req: { fundsUSD: 24000, skills: ['tech', 'business', 'arts'] },
    quota: '无',
    cost: 'RM1,000 申请费',
    difficulty: 2,
    notes: '年收入 24,000 美元即可，主要面向 IT / 数字营销 / 内容创作等远程职业。中文环境友好、生活成本低、时区和国内一致，适合过渡。可带配偶子女。',
    official: 'https://mdec.my/derantau',
  },

  {
    id: 'no-selfemployed',
    country: '挪威', flag: '🇳🇴',
    name: '自雇 / 独立承包人居留', nameEn: 'Residence permit for self-employed persons',
    type: 'nomad',
    duration: '最长 2 年',
    pr: '连续居住满 3 年可申永居',
    req: { minDeg: DEG.bachelor, minEng: ENG.ielts55, fundsUSD: 45000 },
    quota: '无',
    cost: '申请费约 €600，处理周期约 4 个月',
    difficulty: 4,
    notes: '注意：挪威官方并没有叫「数字游民签证」的签证，中文圈说的其实是这条自雇居留。要求本科以上学历或 3 年以上职业培训经历，年收入约 €40,500 以上（对标挪威熟练工最低工资）。可携带配偶子女，需要挪威本地居住地址。收入门槛和生活成本都高，是数字游民签里最贵的一档。',
    official: 'https://www.udi.no/en/want-to-apply/work-immigration/self-employed-person/',
  },
  {
    id: 'hr-nomad',
    country: '克罗地亚', flag: '🇭🇷',
    name: '数字游民居留', nameEn: 'Digital Nomad Residence Permit',
    type: 'nomad',
    duration: '首次最长 18 个月，累计可达 3 年',
    pr: '不通往永居（数字游民居留年限不计入入籍）',
    req: { age: [18, 99], minEng: ENG.daily, fundsUSD: 3600 },
    quota: '无',
    cost: '申请费约 €520',
    difficulty: 2,
    notes: '申根区里门槛较友好的一条，支持全程在线申请，处理周期约 30–60 天。要求每月约 €3,300 以上的境外收入。可带配偶子女，能证明同居 3 年以上的非婚伴侣也可随行。硬性限制是不能在克罗地亚本地就业，且这段居留不累积入籍年限——纯粹是「合法长住」，不是身份路径。',
    official: 'https://mup.gov.hr/aliens-281621/stay-and-work/temporary-stay-of-digital-nomads/286833',
  },
  {
    id: 'si-nomad',
    country: '斯洛文尼亚', flag: '🇸🇮',
    name: '数字游民签证', nameEn: 'Digital Nomad Permit',
    type: 'nomad',
    duration: '1 年，不可续签',
    pr: '不通往永居',
    req: { age: [18, 99], minEng: ENG.daily, fundsUSD: 3300 },
    quota: '无',
    cost: '签证费约 $100 + 落地登记费约 $130 + 医疗保险（保额需 €3 万以上）',
    difficulty: 2,
    notes: '2025 年才推出的新政，申请成本极低。最大的限制是**不可续签**：住满 1 年必须离境，满 6 个月后才能重新申请，所以只适合当作一段体验而非长期落脚。需在使领馆办理，不能落地转。首都卢布尔雅那之外的城市配套对远程工作者不太友好。',
    official: 'https://www.gov.si/en/topics/digital-nomads/',
  },

  // ─────────────── 低成本落脚 / 长住 ───────────────
  {
    id: 'eu-seasonal',
    country: '欧盟', flag: '🇪🇺',
    name: '季节性工作许可', nameEn: 'Seasonal Work Permit',
    type: 'work',
    duration: '12 个月内最长工作 9 个月',
    pr: '本身不通往永居，但可作为转长期工签的跳板',
    req: { age: [18, 99], jobOffer: true, minEng: ENG.daily, skills: ['trades', 'none'] },
    quota: '各成员国分别设限',
    cost: '成本很低，雇主通常提供住宿',
    difficulty: 2,
    notes: '农业采摘、酒店、旅游旺季用工，不要求学历和高语言水平，是成本最低的合法欧洲工作入口之一。可在欧盟官方就业门户 EURES 上直接搜岗位。**风险集中在雇主端**：克扣工资、超时用工、住宿条件恶劣都是常见投诉，务必要求合同写清工作地点、工时、时薪和住宿费用，并确认雇主已购买当地保险。遇到违规保留证据并向当地劳动监察部门投诉。',
    official: 'https://eures.europa.eu/index_en',
  },
  {
    id: 'pl-study',
    country: '波兰', flag: '🇵🇱',
    name: '低成本留学', nameEn: 'Study in Poland',
    type: 'study',
    duration: '学制 3–4 年，毕业后可申请找工作居留',
    pr: '工作满 5 年左右可申永居',
    req: { minDeg: DEG.highschool, minEng: ENG.ielts55, fundsUSD: 6000 },
    quota: '无',
    cost: '部分英语授课项目学费低至每年 $1,000 以内，波兰语项目可免学费',
    difficulty: 2,
    notes: '欧盟境内学费最低的选项之一，雅思 5.0–5.5 就能申。在校期间每周可打工 20 小时，拿的是申根居留，可在其他申根国找工作面试。当地中资企业和欧洲公司分部多，实习就业机会不少。注意各校各专业学费差异很大，务必逐个核实，别信「统一低价」的中介话术。',
    official: 'https://study.gov.pl/',
  },
  {
    id: 'uy-rentista',
    country: '乌拉圭', flag: '🇺🇾',
    name: '自主经济能力居留', nameEn: 'Residencia por medios de vida propios',
    type: 'nomad',
    duration: '直接申请居留，需每年在境内住满 183 天',
    pr: '约 6–12 个月可拿到永居身份证，后续可申请入籍',
    req: { age: [18, 99], fundsUSD: 1800 },
    quota: '无',
    cost: '申请费与证件工本费合计通常在数百美元量级',
    difficulty: 2,
    notes: '门槛结构非常罕见：不看学历、不考语言、不要求投资，只看你有没有稳定收入（约每月 $1,500 以上即可，远程工资、房租、分红都算）。拿身份的速度也快。真正的代价是**居住要求**——每年要在境内住满半年，这对还想在国内发展的人是硬约束。适合已经能远程赚钱、且愿意真的搬过去生活的人。',
    official: 'https://www.gub.uy/ministerio-relaciones-exteriores/',
  },
  {
    id: 'nz-seasonal',
    country: '新西兰', flag: '🇳🇿',
    name: '季节性工作签证', nameEn: 'Seasonal Work Visas',
    type: 'work',
    duration: '高峰季节类最长 7 个月；全球劳动力类最长 3 年',
    pr: '本身不通往永居，但可作为转技术工签的跳板',
    req: { age: [18, 99], jobOffer: true, skills: ['trades', 'none'] },
    quota: '按认证雇主的用工需求',
    cost: '签证费较低',
    difficulty: 2,
    notes: '最大亮点是**不要求英语成绩**，也不看学历，主要面向园艺、农业、葡萄园等季节性用工。分两类：高峰季节签证（短期，最长 7 个月）和全球劳动力季节签证（可反复入境，最长 3 年）。必须先拿到认证雇主的 offer。对英语和学历都不占优势、但愿意做体力工作的人，这是少数还开着的门。政策较新，认证雇主名单和开放时间以移民局公告为准。',
    official: 'https://www.immigration.govt.nz/new-zealand-visas',
  },
  {
    id: 'ec-deposit',
    country: '厄瓜多尔', flag: '🇪🇨',
    name: '存款 / 购房居留', nameEn: 'Investor Residency',
    type: 'invest',
    duration: '2 年临时居留，之后可转永居',
    pr: '临时居留满 21 个月可申永居',
    req: { age: [18, 99], fundsUSD: 47000 },
    quota: '无',
    cost: '存款约 $47,000（2025 年标准），或等值房产',
    difficulty: 2,
    notes: '南美成本最低的投资居留之一，门槛只有约 4.7 万美元且资金是存款不是消费——存满两年可以取出，当地存款利率还有 7–8%。用美元、生活成本低。缺点是治安波动较大，且这条路对回国发展基本没有加成，适合明确想去南美长住或对成本极度敏感的人。金额标准每年随基本工资调整，申请前务必核实当年数字。',
    official: 'https://www.cancilleria.gob.ec/',
  },

  // ─────────────── 创业 / 投资 ───────────────
  {
    id: 'ca-suv',
    country: '加拿大', flag: '🇨🇦',
    name: '创业签证 (SUV)', nameEn: 'Start-up Visa',
    type: 'invest',
    duration: '直接申请永居',
    pr: '是',
    req: { minEng: ENG.ielts55, fundsUSD: 20000 },
    quota: '近年收紧，处理周期被拉长',
    cost: '孵化器/天使投资背书费用常达数万加元，总成本 CAD$100,000+',
    costUSD: 73000,
    difficulty: 4,
    notes: '需要拿到加拿大指定机构（孵化器、天使投资、风投）的支持信。最多 5 个创始人共享一封支持信。近年因申请量暴增，官方设置了年度处理上限，等待期显著变长。市面上大量「包过」中介风险很高。',
    official: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/start-visa.html',
  },
  {
    id: 'uk-innovator',
    country: '英国', flag: '🇬🇧',
    name: '创新创始人签证', nameEn: 'Innovator Founder visa',
    type: 'invest',
    duration: '3 年，可续',
    pr: '3 年可申永居（比工签快 2 年）',
    req: { minEng: ENG.ielts55, fundsUSD: 30000 },
    quota: '无',
    cost: '背书费 + 签证费 + 实际启动资金',
    difficulty: 4,
    notes: '2023 年取消了 £50,000 最低投资额硬性要求，改为由背书机构评估商业计划的创新性、可行性、可扩展性。3 年拿永居是英国最快的路径之一。难点在于通过背书机构的审查。',
    official: 'https://www.gov.uk/innovator-founder-visa',
  },
  {
    id: 'jp-business',
    country: '日本', flag: '🇯🇵',
    name: '经营管理签证', nameEn: 'Business Manager Visa',
    type: 'invest',
    duration: '1 年起，经营稳定后可续 3–5 年',
    pr: '连续居住 10 年可申永住；高度人才路线更快',
    req: { minDeg: DEG.master, otherLang: { code: 'ja', label: '日语 N2' }, fundsUSD: 200000 },
    quota: '无',
    cost: '注册资本大幅提高，加上实体办公室、会计与顾问费用，前期投入常在 3,000 万日元以上',
    difficulty: 4,
    notes: '⚠️ 门槛已被大幅收紧，网上大量「500 万日元开公司拿身份」的攻略都已作废。改革后对注册资本、经营实体性、申请人学历与日语能力都提出了明确要求（普遍要求硕士以上学历或相关领域专业资历、日语 N2 以上），并设有过渡期安排。这条路现在只适合真的要在日本做生意的人，不再是低成本身份方案。具体要件与过渡期截止日以入管厅最新公告为准。',
    official: 'https://www.moj.go.jp/isa/applications/status/business-manager.html',
  },
  {
    id: 'ae-golden',
    country: '阿联酋', flag: '🇦🇪',
    name: '黄金签证', nameEn: 'UAE Golden Visa',
    type: 'invest',
    duration: '5–10 年，可续',
    pr: '长期居留，但不通往国籍',
    req: { fundsUSD: 545000 },
    quota: '无',
    cost: '房产投资 200 万迪拉姆起，或走人才类别',
    difficulty: 3,
    notes: '零个人所得税是最大卖点。除投资路径外，还有人才类别（科学家、医生、程序员、创作者等）可以低成本申请，程序员类别对有一定履历的 IT 从业者比较友好。不通往国籍，是纯粹的「税务 + 生活」选择。',
    official: 'https://u.ae/en/information-and-services/visa-and-emirates-id/residence-visas/golden-visa',
  },
];

/** 简单的一致性自检，帮助贡献者在浏览器控制台里发现数据问题。 */
function validatePathways() {
  const seen = new Set();
  const problems = [];
  for (const p of PATHWAYS) {
    if (seen.has(p.id)) problems.push(`重复 id: ${p.id}`);
    seen.add(p.id);
    for (const f of ['country', 'name', 'type', 'duration', 'notes', 'official']) {
      if (!p[f]) problems.push(`${p.id} 缺少字段 ${f}`);
    }
    if (!TYPE_LABEL[p.type]) problems.push(`${p.id} 的 type "${p.type}" 未定义`);
    if (!REGION_OF[p.country]) problems.push(`${p.id} 的国家「${p.country}」未归入地区，请补 REGION_OF`);
  }
  return problems;
}
