/**
 * 大学生专题独立数据集。
 *
 * 这里不引用主站 PATHWAYS：学生路径里有课程、培训、J-1、互惠生和
 * 换宿平台，不能都塞进同一个“签证”模型。目标站只作为二手线索，
 * 文案重新整理，资格判断优先指向官方来源。
 */

const STUDENT_TYPES = {
  visa: '签证 / 居留',
  education: '留学 / 课程',
  training: '职业培训',
  internship: '实习 / 交流',
  workholiday: '打工度假',
  aupair: '互惠生',
  employment: '工作',
  platform: '平台线索（不是签证）',
  longStay: '长期停留',
};

const STUDENT_REGIONS = {
  asia: '亚洲', europe: '欧洲', northAmerica: '北美', oceania: '大洋洲',
  latinAmerica: '拉美', global: '全球 / 多国',
};

const STUDENT_QUESTIONS = [
  {
    id: 'stage', label: '你现在处在哪个阶段？',
    hint: '在读和毕业后的窗口期，决定不少学生项目能不能申请。',
    type: 'radio', required: true,
    options: [
      { value: 'college', label: '在读大专' },
      { value: 'university', label: '在读本科' },
      { value: 'graduate', label: '在读硕博' },
      { value: 'recent', label: '毕业 12 个月内' },
      { value: 'alumni', label: '毕业超过 1 年' },
    ],
  },
  {
    id: 'education', label: '最高学历 / 预计学历？', type: 'radio', required: true,
    options: [
      { value: 'highschool', label: '高中 / 中专' },
      { value: 'college', label: '大专' },
      { value: 'bachelor', label: '本科' },
      { value: 'master', label: '硕士及以上' },
    ],
  },
  {
    id: 'age', label: '年龄', hint: '不同国家的青年项目年龄上限差别很大。', type: 'number', required: true,
  },
  {
    id: 'english', label: '英语大概到什么程度？', type: 'radio', required: true,
    options: [
      { value: 'none', label: '几乎不会' },
      { value: 'daily', label: '能日常交流' },
      { value: 'ielts55', label: '约 IELTS 5.5' },
      { value: 'ielts65', label: '约 IELTS 6.5' },
      { value: 'fluent', label: '能全英文学习 / 工作' },
    ],
  },
  {
    id: 'japanese', label: '日语水平', hint: '不会也可以选“不会”；语言学校和特定技能的要求不同。', type: 'radio', required: true,
    options: [
      { value: 'none', label: '不会' },
      { value: 'beginner', label: '入门 / N5' },
      { value: 'n4', label: 'N4 左右' },
      { value: 'n3', label: 'N3 左右' },
      { value: 'n2', label: 'N2 及以上' },
    ],
  },
  {
    id: 'german', label: '德语水平', type: 'radio', required: true,
    options: [
      { value: 'none', label: '不会' },
      { value: 'a2', label: 'A1–A2' },
      { value: 'b1', label: 'B1' },
      { value: 'b2', label: 'B2 及以上' },
    ],
  },
  {
    id: 'cash', label: '现在能拿出的启动资金？', hint: '这是现金，不等于签证要求的存款证明，也不等于全年总成本。', type: 'radio', required: true,
    options: [
      { value: 'under1', label: '1 万元以内' },
      { value: '1to3', label: '1–3 万元' },
      { value: '3to8', label: '3–8 万元' },
      { value: '8to20', label: '8–20 万元' },
      { value: 'over20', label: '20 万元以上' },
    ],
  },
  {
    id: 'tuition', label: '能承受的学费 / 项目费？', type: 'radio', required: true,
    options: [
      { value: 'zero', label: '尽量不花（希望有工资 / 奖学金）' },
      { value: 'low', label: '每年 3 万以内' },
      { value: 'mid', label: '每年 3–10 万' },
      { value: 'high', label: '每年 10 万以上' },
    ],
  },
  {
    id: 'study', label: '你愿意通过读书或培训出去吗？', type: 'radio', required: true,
    options: [
      { value: 'language', label: '可以读语言课程' },
      { value: 'vocational', label: '可以读职业培训' },
      { value: 'degree', label: '可以读大专 / 本科 / 硕士' },
      { value: 'short', label: '只接受短期课程 / 实习' },
      { value: 'none', label: '不想再读书' },
    ],
  },
  {
    id: 'offer', label: '手上已有哪类确定条件？', hint: '没有就选“暂时没有”，不会因此把所有路径判死。', type: 'radio', required: true,
    options: [
      { value: 'school', label: '海外学校录取' },
      { value: 'employer', label: '海外雇主 offer' },
      { value: 'training', label: '职业培训合同' },
      { value: 'sponsor', label: '实习 / 交流 sponsor' },
      { value: 'none', label: '暂时没有' },
    ],
  },
  {
    id: 'goals', label: '你更在意什么？', hint: '可多选，只影响排序和提示，不直接决定资格。', type: 'checkbox',
    options: [
      { value: 'leaveFast', label: '尽快先合法出去' },
      { value: 'work', label: '先工作积累经验' },
      { value: 'skill', label: '学一门能吃饭的技能' },
      { value: 'pr', label: '以后争取长期留下' },
      { value: 'english', label: '提升英语和国际经历' },
      { value: 'lowCost', label: '预算越低越好' },
    ],
  },
  {
    id: 'limits', label: '有哪些现实限制？', hint: '可多选；勾上后会过滤或降低对应路径，但不会替你做法律判断。', type: 'checkbox',
    options: [
      { value: 'noHighTuition', label: '不能承担高学费' },
      { value: 'noHostFamily', label: '不接受寄宿家庭' },
      { value: 'noManual', label: '不接受农业 / 餐饮 / 体力劳动' },
      { value: 'noRemote', label: '不想去偏远地区' },
      { value: 'noLanguageExam', label: '不想参加语言考试' },
      { value: 'noShortStay', label: '不接受短期、不可续的身份' },
    ],
  },
];

const STUDENT_PATHWAYS = [
  {
    id: 'jp-language-school', country: '日本', flag: '🇯🇵', region: 'asia',
    title: '日本语言学校留学', officialName: 'Student status · Japanese language school',
    type: 'education', legalNature: 'education',
    tags: ['高中可申', '日语入门', '可合法兼职'],
    summary: '先用学生身份进入日本，再决定升学、转工作签还是回国。它是留学路径，不是“去了就能留下”的保证。',
    requirements: { age: '资料页列 18–35 岁，年龄需向学校和入管确认', education: '高中 / 中专及以上', language: 'N5 或约 150 小时学习证明', stage: '高中毕业或在读', offer: '语言学校录取' },
    costs: { currency: '人民币 / 日元', proofOfFunds: '资料页约 3–5 万元等值存款证明，按学校和入管要求核实', tuition: '约 60–80 万日元 / 年（页面数据，需逐校核对）', visaFee: '以使领馆最新标准为准', startup: '资料页估算 5 万元起，不含全年真实生活费' },
    timeline: { preparation: '国内准备约 3–6 个月', processing: '约 2–4 个月', duration: '语言学校最长约 2 年，升学后可延长' },
    workRights: '取得资格外活动许可后，每周最多 28 小时；长假期间规则不同。',
    workRestrictions: '兼职不能替代全部学费；出勤率过低可能影响续签和升学。',
    followOn: '升大学 / 专门学校，或找到符合条件的工作后转“技人国”等工作身份。',
    quota: '无统一固定名额，但学校与入管会审核材料。',
    officialLinks: [
      { label: '日本出入国在留管理厅：在留资格「留学」', url: 'https://www.moj.go.jp/isa/applications/status/student.html' },
      { label: 'Study in Japan 官方信息', url: 'https://www.studyinjapan.go.jp/en/' },
    ],
    secondaryLinks: [{ label: '参考路径页（海外路径）', url: 'https://overseas-pathways.pages.dev/pathways/japan-student-visa/' }],
    verifiedAt: '2026-09', confidence: 'review',
    branches: [{ id: 'school', label: '语言学校学生身份', checks: [
      { kind: 'soft', label: '学校录取', test: p => p.offer === 'school', gap: '还没有语言学校录取，需要先申请学校。' },
      { kind: 'soft', label: '启动资金', test: p => !['under1'].includes(p.cash), gap: '启动资金低于资料页的初筛区间，需重新核算学费、住宿和生活费。' },
      { kind: 'soft', label: '学习意愿', test: p => ['language', 'degree'].includes(p.study), gap: '你选择了不再读书，这条路径的前提是接受语言课程。' },
    ] }],
    steps: ['确认目标学校与入学期', '准备学历、成绩、资金和就学理由材料', '由学校协助申请在留资格认定证明书', '拿到 COE 后申请签证并入境', '办理在留卡、住民登记和资格外活动许可', '在出勤与学习合规的前提下规划升学或转工作身份'],
    documents: ['护照', '毕业证 / 在读证明与成绩单', '资金证明及资助关系材料', '就学理由书 / 学习计划', '学校要求的照片与其他表格'],
    pitfalls: ['页面部分费用数字存在明显格式或口径问题，不能照抄总价。', '出勤率是续签和升学的关键，不要把打工当成主线。', '中介费不是签证费，先向学校确认是否可以直接申请。'],
    faq: [{ q: '日语零基础能申请吗？', a: '部分学校接受零基础，但通常需要 N5 或学习时数证明；以目标学校和入管要求为准。' }],
    attribution: { inspirationSource: 'https://overseas-pathways.pages.dev/pathways/japan-student-visa/', sourceType: 'secondary-reference', notAuthoritative: true },
  },
  {
    id: 'ca-coop', country: '加拿大', flag: '🇨🇦', region: 'northAmerica',
    title: '加拿大公立学院 + Co-op', officialName: 'Study permit with co-op placement',
    type: 'education', legalNature: 'education',
    tags: ['课程含实习', '学院路线', '需学签审核'],
    summary: 'Co-op 是课程中的实习安排，不是一张单独的“移民签证”。能否实习、毕业后能否申请 PGWP，要逐校逐项目核实。',
    requirements: { age: '无统一上限，个案审核', education: '高中及以上（项目不同）', language: '学院项目常见 IELTS 6.0 左右，按学校核实', stage: '可申请在读或毕业生', offer: 'DLI 学校录取；Co-op 项目需符合学校与移民规则' },
    costs: { currency: '加元 / 人民币', proofOfFunds: '需证明学费与生活费，具体金额按当年 IRCC 标准', tuition: '页面估算公立学院约 CAD 14,000–18,000 / 年，逐校核对', visaFee: '学签与生物识别费按 IRCC 最新标准', startup: '页面估算 8 万元起，不代表全年总成本' },
    timeline: { preparation: '选校与材料约 2–4 个月', processing: '学签审理时间随国家和个案变化', duration: '课程期间；毕业后的工作许可另按当年资格判断' },
    workRights: '学习期间的校外工作权限和 Co-op 实习权限分别适用不同规则，必须看学签、课程和官方页面。',
    workRestrictions: 'Co-op 实习不能自动等同于毕业工签；PGWP 资格受学校、课程长度、专业和当年政策影响。',
    followOn: '可能衔接 PGWP、加拿大本地工作经验、CEC 或省提名，但不保证。',
    quota: '学校录取和学签均非“抢到就稳”，学签会审核学习计划与资金。',
    officialLinks: [
      { label: 'IRCC：学习期间工作', url: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/work/while-you-study.html' },
      { label: 'IRCC：毕业后工签 PGWP', url: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/work/after-graduation/about.html' },
    ],
    secondaryLinks: [{ label: '参考路径页（海外路径）', url: 'https://overseas-pathways.pages.dev/pathways/canada-coop/' }],
    verifiedAt: '2026-09', confidence: 'review',
    branches: [{ id: 'study', label: '学院课程 + Co-op', checks: [
      { kind: 'soft', label: '学校录取', test: p => p.offer === 'school', gap: '需要先获得符合条件的 DLI 学校 / 项目录取。' },
      { kind: 'soft', label: '学费承受力', test: p => ['mid', 'high'].includes(p.tuition), gap: '当前学费预算偏低，需先核算学费、生活费和资金证明。' },
      { kind: 'soft', label: '英语', test: p => ['ielts55', 'ielts65', 'fluent'].includes(p.english), gap: '语言水平可能低于常见学院项目要求，需按学校确认。' },
      { kind: 'soft', label: '愿意读书', test: p => p.study === 'degree', gap: 'Co-op 依附于课程，你需要接受先读书。' },
    ] }],
    steps: ['确认学校是否为 DLI、课程是否含真实 Co-op', '分别核对学签、Co-op 实习和 PGWP 资格', '准备学习计划、资金和学历材料', '申请学签并按许可范围学习 / 实习', '毕业前再次核对 PGWP 与后续身份条件'],
    documents: ['学校录取与课程说明', '学习计划', '资金证明与资助材料', '学历、成绩单、语言成绩', '护照、体检和生物识别材料（按 IRCC 要求）'],
    pitfalls: ['“含 Co-op”不等于“毕业一定有工签”。', '页面中的通过率、工资和移民配额数字不是官方保证，不能当成功率。', '不要为了移民目的写与真实学习计划不符的材料。'],
    faq: [{ q: 'Co-op 是签证吗？', a: '不是。它通常是课程中的实习安排；学签、实习许可和毕业后工签是不同问题。' }],
    attribution: { inspirationSource: 'https://overseas-pathways.pages.dev/pathways/canada-coop/', sourceType: 'secondary-reference', notAuthoritative: true },
  },
  {
    id: 'de-ausbildung', country: '德国', flag: '🇩🇪', region: 'europe',
    title: '德国双元制 Ausbildung', officialName: 'Duale Berufsausbildung',
    type: 'training', legalNature: 'training', tags: ['免学费倾向', '培训期有津贴', '德语是门槛'],
    summary: '企业工作与职业学校结合的培训路线。学历不是唯一门槛，德语和培训合同才是现实中的核心。',
    requirements: { age: '页面列 18–35 岁，实际无统一年龄硬线但年龄影响录取', education: '高中及以上常见', language: '德语 B1–B2，专业不同', stage: '毕业生和转行者可查', offer: '必须先拿培训合同' },
    costs: { currency: '欧元 / 人民币', proofOfFunds: '视培训津贴是否覆盖生活费和签证要求而定', tuition: '正规培训通常不收传统学费', visaFee: '按使领馆最新标准', startup: '页面估算约 3 万元起，需另算语言学习成本' },
    timeline: { preparation: '从零到 B1 常需 8–14 个月', processing: '拿合同后签证通常还需数周至数月', duration: '约 2–3.5 年；结业后再按工作身份规划' },
    workRights: '培训期间按培训合同和居留许可工作，企业支付培训津贴。',
    workRestrictions: '培训合同不等于永久工作权；换企业、离开培训或从事额外工作都要先确认规则。',
    followOn: '结业后可寻找符合条件的工作身份，永居要求按当年法律和个人缴费/居留情况核实。',
    quota: '无统一全国名额，取决于企业岗位与录取。',
    officialLinks: [
      { label: 'Make it in Germany：职业培训', url: 'https://www.make-it-in-germany.com/en/study-training/training' },
      { label: '德国联邦劳工局职位搜索', url: 'https://www.arbeitsagentur.de/jobsuche/' },
    ],
    secondaryLinks: [{ label: '参考路径页（海外路径）', url: 'https://overseas-pathways.pages.dev/pathways/germany-ausbildung/' }],
    verifiedAt: '2026-09', confidence: 'review',
    branches: [{ id: 'training', label: '企业培训合同', checks: [
      { kind: 'soft', label: '培训合同', test: p => p.offer === 'training', gap: '需要先取得德国企业培训合同，不能只凭兴趣申请。' },
      { kind: 'soft', label: '德语', test: p => ['b1', 'b2'].includes(p.german), gap: '德语尚未到常见培训岗位要求，护理等岗位可能需要更高。' },
      { kind: 'soft', label: '愿意职业培训', test: p => p.study === 'vocational', gap: '这条路的核心就是职业培训，你需要接受边工作边学习。' },
    ] }],
    steps: ['确定职业方向与德语目标', '在官方职位渠道寻找 Ausbildungsplatz', '通过面试并签订培训合同', '准备签证、学历和保险材料', '入境后完成企业与职业学校双轨培训', '结业后按工作合同规划下一步身份'],
    documents: ['德语证书', '培训合同', '学历与成绩单', '简历和动机信', '签证及保险材料'],
    pitfalls: ['把“免学费”误认为“零成本”，语言、房租、机票和签证仍需资金。', '中介不能替代企业合同，警惕收高额“保录取费”。', '培训津贴和岗位条件地域差异很大。'],
    faq: [{ q: '没有大学学历能不能走？', a: '部分职业培训岗位以高中或职业教育为基础，但具体资格由岗位、企业和签证要求共同决定。' }],
    attribution: { inspirationSource: 'https://overseas-pathways.pages.dev/pathways/germany-ausbildung/', sourceType: 'secondary-reference', notAuthoritative: true },
  },
  {
    id: 'au-whv-462', country: '澳大利亚', flag: '🇦🇺', region: 'oceania',
    title: '澳大利亚 Work and Holiday 462', officialName: 'Work and Holiday visa (subclass 462)',
    type: 'workholiday', legalNature: 'visa', tags: ['18–30 岁', '抽签 / 名额', '不需先找工作'],
    summary: '先拿青年流动签证，再在澳洲工作和旅行。对学生来说是短期体验与攒海外经验，不是自动移民通道。',
    requirements: { age: '申请时通常 18–30 岁', education: '大专或本科阶段要求按当年规则', language: '基础英语证明', stage: '学生或应届生可关注', offer: '不需要提前拿雇主 offer' },
    costs: { currency: '澳元 / 人民币', proofOfFunds: '需资金证明，金额以当年官方要求为准', tuition: '不是留学项目', visaFee: '以澳洲内政部最新费用为准', startup: '需另算机票、保险与落地生活费' },
    timeline: { preparation: '提前准备护照、语言和资金材料', processing: '先按当年窗口注册 / 预申请，再按邀请递交', duration: '首次通常 12 个月；续签条件另查' },
    workRights: '可在许可范围内工作和旅行。', workRestrictions: '雇主、学习时长、续签指定工作等限制必须按当年签证条件核对。',
    followOn: '可积累工作和语言经验，后续身份需要另行申请，不等于自动获得永居。', quota: '中国大陆申请人有年度安排，机制和窗口可能调整。',
    officialLinks: [{ label: '澳大利亚内政部：462', url: 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/work-holiday-462' }],
    secondaryLinks: [{ label: '参考路径页（海外路径）', url: 'https://overseas-pathways.pages.dev/pathways/australia-whv-462/' }],
    verifiedAt: '2026-09', confidence: 'review',
    branches: [{ id: 'whv', label: '青年流动签证', checks: [
      { kind: 'hard', label: '年龄', test: p => p.age >= 18 && p.age <= 30, gap: '年龄可能超出 462 的申请窗口，按递交日规则核实。' },
      { kind: 'soft', label: '英语', test: p => ['ielts55', 'ielts65', 'fluent'].includes(p.english), gap: '需要准备符合官方认可范围的英语证明。' },
      { kind: 'soft', label: '启动资金', test: p => p.cash !== 'under1', gap: '落地成本和资金证明不能只按签证费估算。' },
      { kind: 'soft', label: '抽签窗口', test: p => true, gap: '' },
    ] }],
    steps: ['查看当年中国申请人的官方窗口与机制', '准备英语、学历、护照和资金材料', '按官方系统完成注册 / 预申请', '获邀后在规定期限内提交正式申请', '下签后购买保险并规划落地工作'],
    documents: ['护照', '学历材料', '英语证明', '资金证明', '健康与品格材料（按通知）'],
    pitfalls: ['抽签或配额不是成功率，任何“内部名额”都是危险信号。', '打工度假签不等于永居，续签与后续身份要另查。', '页面里的工资和存钱估计是经验值，不是保证。'],
    faq: [{ q: '必须先找到工作吗？', a: '通常不需要先有雇主 offer，但入境后的工作仍需遵守签证条件。' }],
    attribution: { inspirationSource: 'https://overseas-pathways.pages.dev/pathways/australia-whv-462/', sourceType: 'secondary-reference', notAuthoritative: true },
  },
  {
    id: 'nz-whv', country: '新西兰', flag: '🇳🇿', region: 'oceania',
    title: '新西兰中国打工度假签', officialName: 'China Working Holiday Visa',
    type: 'workholiday', legalNature: 'visa', tags: ['18–30 岁', '先到先得', '名额少'],
    summary: '名额型青年签证，适合愿意做季节性工作、接受户外生活的年轻人。最难的往往不是材料，而是抢到窗口。',
    requirements: { age: '通常 18–30 岁', education: '高中及以上常见', language: '英语门槛按当年规则', stage: '在读 / 应届可准备', offer: '不需要预先雇主 offer' },
    costs: { currency: '新西兰元 / 人民币', proofOfFunds: '需资金证明，按官方当年金额', tuition: '不是留学项目', visaFee: '按移民局最新费用', startup: '另算体检、机票、保险与首月生活费' },
    timeline: { preparation: '提前准备账号和材料', processing: '抢到名额后再按要求递交', duration: '通常 12 个月，延期条件另查' },
    workRights: '可在许可范围内工作、学习和旅行。', workRestrictions: '不能把临时工作当永久雇佣；指定工作与延期条件需按当年页面核对。', followOn: '可作为海外经历和后续找工作的起点，但不自动转永居。', quota: '中国申请人年度名额有限，开放时间可能变化。',
    officialLinks: [{ label: '新西兰移民局：中国打工度假签', url: 'https://www.immigration.govt.nz/new-zealand-visas/visas/visa/china-working-holiday-visa' }],
    secondaryLinks: [{ label: '参考路径页（海外路径）', url: 'https://overseas-pathways.pages.dev/pathways/new-zealand-whv/' }],
    verifiedAt: '2026-09', confidence: 'review',
    branches: [{ id: 'whv', label: '名额型青年签证', checks: [
      { kind: 'hard', label: '年龄', test: p => p.age >= 18 && p.age <= 30, gap: '年龄可能超出中国打工度假签窗口。' },
      { kind: 'soft', label: '启动资金', test: p => !['under1'].includes(p.cash), gap: '需要准备资金证明和落地生活费。' },
      { kind: 'soft', label: '接受季节工作', test: p => !p.limits.includes('noManual'), gap: '你排除了农业 / 体力工作，而这是常见就业方向。' },
    ] }],
    steps: ['确认当年开放日期和中国申请人条件', '提前注册账户、准备护照与资金材料', '开放后按规则申请名额', '取得资格后完成材料、体检和签证流程', '落地后按签证条件工作和旅行'],
    documents: ['护照', '资金证明', '学历 / 语言材料（如要求）', '健康和品格材料'],
    pitfalls: ['“先到先得”没有内部通道，任何代抢承诺都需警惕。', '户外工作受季节影响明显，别只按网上月收入估算。', '这是一年期青年项目，不是自动移民。'],
    faq: [{ q: '抢不到名额怎么办？', a: '只能关注下一次官方窗口，或重新评估留学、培训和其他合法路径。' }],
    attribution: { inspirationSource: 'https://overseas-pathways.pages.dev/pathways/new-zealand-whv/', sourceType: 'secondary-reference', notAuthoritative: true },
  },
  {
    id: 'ie-whv', country: '爱尔兰', flag: '🇮🇪', region: 'europe',
    title: '爱尔兰 Working Holiday Authorisation', officialName: 'Working Holiday Authorisation',
    type: 'workholiday', legalNature: 'visa', tags: ['英语环境', '青年项目', '可查工作许可衔接'],
    summary: '在英语环境里短期工作和生活，再观察自己是否适合欧洲职场。名额、国籍资格和申请窗口必须看当年公告。',
    requirements: { age: '通常 18–30 岁', education: '大专及以上或在读本科条件需核实', language: '英语证明按当年要求', stage: '学生 / 应届生重点关注', offer: '通常无需提前雇主 offer' },
    costs: { currency: '欧元 / 人民币', proofOfFunds: '需资金证明', tuition: '可学习短期课程，时长按规则', visaFee: '按爱尔兰官方要求', startup: '另算机票、保险和都柏林房租' },
    timeline: { preparation: '约 2–3 个月准备材料', processing: '通常需数周至数月', duration: '通常 12 个月，不可直接延长' },
    workRights: '在 authorisation 范围内从事合法工作并短期学习。', workRestrictions: '不能把 WHA 当作长期工作许可；转 Employment Permit 需另满足条件。', followOn: '有机会以雇主和职业条件为基础转工作许可，但不保证。', quota: '中国大陆名额和窗口以爱尔兰当年公告为准。',
    officialLinks: [{ label: '爱尔兰外交部：Working Holiday', url: 'https://www.ireland.ie/en/dfa/visas-for-ireland/working-holiday-authorisation/' }],
    secondaryLinks: [{ label: '参考路径页（海外路径）', url: 'https://overseas-pathways.pages.dev/pathways/ireland-whv/' }],
    verifiedAt: '2026-09', confidence: 'review',
    branches: [{ id: 'wha', label: '爱尔兰青年项目', checks: [
      { kind: 'hard', label: '年龄', test: p => p.age >= 18 && p.age <= 30, gap: '年龄可能超出该青年项目窗口。' },
      { kind: 'soft', label: '英语', test: p => ['ielts55', 'ielts65', 'fluent'].includes(p.english), gap: '英语水平不足以稳妥应对申请和落地生活，需按官方证明要求核对。' },
      { kind: 'soft', label: '资金', test: p => p.cash !== 'under1', gap: '需要准备资金证明、保险与落地住宿。' },
    ] }],
    steps: ['确认当年中国申请资格和配额', '准备学历、英语、资金和护照材料', '在官方窗口递交申请', '获得 authorisation 后规划保险、住宿和工作'],
    documents: ['护照', '学历或在读证明', '资金证明', '保险和品格材料（按公告）'],
    pitfalls: ['爱尔兰是欧盟国家，但 WHA 不等于欧盟自由工作权。', '都柏林住房成本可能显著高于签证费。', '“能转工签”取决于职业、雇主和 Employment Permit 规则。'],
    faq: [{ q: '不会爱尔兰语能生活吗？', a: '日常工作和生活主要使用英语，但具体岗位仍有各自要求。' }],
    attribution: { inspirationSource: 'https://overseas-pathways.pages.dev/pathways/ireland-whv/', sourceType: 'secondary-reference', notAuthoritative: true },
  },
  {
    id: 'au-vet', country: '澳大利亚', flag: '🇦🇺', region: 'oceania',
    title: '澳大利亚 VET / TAFE 职业教育', officialName: 'Vocational Education and Training',
    type: 'education', legalNature: 'education', tags: ['职业技能', '课程选择重要', '成本可能较高'],
    summary: '以职业课程为入口的留学路线。课程是否适合后续工作或身份，不能只看“TAFE”三个字，要逐校逐专业核验。',
    requirements: { age: '无统一上限，学习计划很重要', education: '高中 / 大专 / 本科视课程', language: '按学校和签证要求', stage: '学生和转行者可查', offer: '需要课程录取' },
    costs: { currency: '澳元 / 人民币', proofOfFunds: '学签需证明学费和生活费', tuition: '课程差异很大，不能用单一数字代表', visaFee: '按澳洲内政部最新标准', startup: '通常明显高于打工度假，需完整预算' },
    timeline: { preparation: '选校与材料数月', processing: '学签时间随个案变化', duration: '课程长度按项目，毕业后工作权另查' },
    workRights: '按学生签证和课程条件工作。', workRestrictions: '课程不自动带来移民资格；工作权、毕业工签和职业清单必须分别核实。', followOn: '可能衔接毕业后工作许可或雇主路径，取决于项目和职业。', quota: '学签和学校招生均需个案审核。',
    officialLinks: [{ label: '澳洲内政部：学生签证', url: 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500' }, { label: 'Study Australia 官方', url: 'https://www.studyaustralia.gov.au/' }],
    secondaryLinks: [{ label: '参考路径目录（海外路径）', url: 'https://overseas-pathways.pages.dev/pathways/' }],
    verifiedAt: '2026-09', confidence: 'needs-confirmation',
    branches: [{ id: 'vet', label: '职业课程', checks: [
      { kind: 'soft', label: '课程录取', test: p => p.offer === 'school', gap: '需要先取得学校和具体课程录取。' },
      { kind: 'soft', label: '学费预算', test: p => ['mid', 'high'].includes(p.tuition), gap: '当前学费预算可能不足，需按目标课程重算。' },
      { kind: 'soft', label: '愿意读书', test: p => ['degree', 'vocational'].includes(p.study), gap: 'VET 是课程路线，需要接受先学习再规划工作。' },
    ] }],
    steps: ['明确职业目标而不是只选学校品牌', '确认 CRICOS、课程、工作权和毕业后资格', '准备学习计划与资金', '申请学签并遵守课程与工作条件', '毕业前重新核对后续身份'],
    documents: ['录取信', '学习计划', '学历、成绩单、语言', '资金、健康和品格材料'],
    pitfalls: ['TAFE 不是统一移民项目，课程之间差异很大。', '不能把学校宣传中的“就业”理解成签证保证。', '澳洲生活成本、保险和学费要一起算。'],
    faq: [{ q: 'VET 一定比大学便宜吗？', a: '具体取决于学校、课程和城市；不能用一个“职业教育便宜”的概念替代预算。' }],
    attribution: { inspirationSource: 'https://overseas-pathways.pages.dev/pathways/australia-vet-tafe/', sourceType: 'secondary-reference', notAuthoritative: true },
  },
  {
    id: 'us-j1-itp', country: '美国', flag: '🇺🇸', region: 'northAmerica',
    title: '美国 J-1 Intern / Trainee', officialName: 'Exchange Visitor Program · Intern / Trainee',
    type: 'internship', legalNature: 'internship', tags: ['有薪实习', '需要 sponsor', '不是普通工签'],
    summary: '通过国务院指定 sponsor 做结构化实习或培训。适合在读生、应届生和有相关经验的新人，但 J-1 不是移民签证。',
    requirements: { age: '页面列 18–40 岁，实际看 sponsor 与项目', education: 'Intern 在读 / 近期毕业；Trainee 需学位与经验等', language: '能完成全英文工作和面试', stage: 'Intern 与 Trainee 分支不同', offer: '需要 sponsor + Host Company + Training Plan' },
    costs: { currency: '美元 / 人民币', proofOfFunds: '需证明前期生活能力', tuition: '不是学位课程', visaFee: 'SEVIS、签证和 sponsor 费用按当年标准', startup: '页面估算 2 万元起，机构费差异大' },
    timeline: { preparation: '寻找 sponsor 与 host 需数月', processing: '材料完整后仍需签证面签', duration: 'Intern 最长通常 12 个月；Trainee 通常最长 18 个月' },
    workRights: '只能在 DS-7002 Training Plan 约定的 Host Company 和岗位内实习 / 培训。', workRestrictions: '不能把 J-1 当 H-1B；部分项目可能涉及 212(e) 两年回国居住要求。', followOn: '结束后需按规则离境或另行转换身份，不自动转 H-1B / 绿卡。', quota: '无统一总名额，但 sponsor 有各自审核和容量。',
    officialLinks: [{ label: '美国国务院：Intern', url: 'https://j1visa.state.gov/programs/intern/' }, { label: '美国国务院：Trainee', url: 'https://j1visa.state.gov/programs/trainee/' }],
    secondaryLinks: [{ label: '参考路径页（海外路径）', url: 'https://overseas-pathways.pages.dev/pathways/usa-j1-itp/' }],
    verifiedAt: '2026-09', confidence: 'review',
    branches: [
      { id: 'intern', label: 'Intern', checks: [
        { kind: 'hard', label: '学生阶段', test: p => ['college', 'university', 'graduate', 'recent'].includes(p.stage), gap: 'Intern 通常要求在读或毕业不久，毕业窗口需按 sponsor 核实。' },
        { kind: 'soft', label: 'Sponsor / Host', test: p => ['sponsor', 'employer'].includes(p.offer), gap: '需要国务院指定 sponsor 和 Host Company。' },
        { kind: 'soft', label: '英语', test: p => ['ielts55', 'ielts65', 'fluent'].includes(p.english), gap: '需要能完成全英文工作环境和面试。' },
      ] },
      { id: 'trainee', label: 'Trainee', checks: [
        { kind: 'soft', label: '相关经验', test: p => ['recent', 'alumni'].includes(p.stage) && p.education !== 'highschool', gap: 'Trainee 需要按学位与相关经验条件核实。' },
        { kind: 'soft', label: 'Sponsor / Host', test: p => ['sponsor', 'employer'].includes(p.offer), gap: '需要 sponsor、Host Company 和 Training Plan。' },
        { kind: 'soft', label: '英语', test: p => ['ielts55', 'ielts65', 'fluent'].includes(p.english), gap: '需要能完成全英文培训与工作。' },
      ] },
    ],
    steps: ['判断自己更接近 Intern 还是 Trainee', '寻找国务院指定 sponsor 与 Host Company', '确认 Training Plan（DS-7002）内容', '取得 DS-2019 后缴费、填 DS-160 并面签', '按计划完成实习，提前规划结束后的离境或身份'],
    documents: ['护照', '在读 / 学位与成绩单', '英文简历与推荐信', 'Host Company Offer', 'DS-7002、DS-2019、SEVIS 收据'],
    pitfalls: ['J-1 的本质是交流访问与培训，不是普通工作签。', 'Sponsor 收费差别大，应查国务院指定名单和合同。', '212(e) 是否适用必须向 sponsor 确认。'],
    faq: [{ q: '没有工作经验能走吗？', a: '部分在读生或近期毕业生可以走 Intern 分支，但仍需专业相关、Host Company 和 sponsor。' }],
    attribution: { inspirationSource: 'https://overseas-pathways.pages.dev/pathways/usa-j1-itp/', sourceType: 'secondary-reference', notAuthoritative: true },
  },
  {
    id: 'nl-aupair', country: '荷兰', flag: '🇳🇱', region: 'europe',
    title: '荷兰 Au Pair 互惠生', officialName: 'Au pair residence permit',
    type: 'aupair', legalNature: 'aupair', tags: ['寄宿家庭', '年龄窗口', '不是普通工作'],
    summary: '住在寄宿家庭、做有限的家庭协助并体验语言文化。它不是普通雇佣，更不是一条可以随意打工的签证。',
    requirements: { age: '通常有严格年龄窗口，按 IND 当年规则', education: '基础学历与个人条件按项目', language: '基础沟通能力', stage: '年轻申请人重点关注', offer: '需要认可 sponsor / 寄宿家庭' },
    costs: { currency: '欧元 / 人民币', proofOfFunds: '按 sponsor 和居留要求', tuition: '通常不是正式学位学费', visaFee: '按 IND 要求', startup: '需另算保险、交通与个人生活费' },
    timeline: { preparation: '寻找家庭与 sponsor 需时间', processing: '按 IND 和 sponsor 流程', duration: '通常为有限期居留，不等同长期工签' },
    workRights: '仅限互惠生安排中约定的家庭协助和语言文化活动。', workRestrictions: '不能在家庭外自由接普通工作；小时数和任务有明确限制。', followOn: '结束后需离境或另行申请其他身份。', quota: '以认可 sponsor 与当年规则为准。',
    officialLinks: [{ label: '荷兰 IND：Au pair', url: 'https://ind.nl/en/residence-permits/au-pair-and-exchange/au-pair' }],
    secondaryLinks: [{ label: '参考路径页（海外路径）', url: 'https://overseas-pathways.pages.dev/pathways/netherlands-au-pair/' }],
    verifiedAt: '2026-09', confidence: 'review',
    branches: [{ id: 'host', label: '寄宿家庭安排', checks: [
      { kind: 'hard', label: '年龄窗口', test: p => p.age >= 18 && p.age <= 30, gap: '互惠生通常有严格年龄窗口，需按 IND 当年规则核对。' },
      { kind: 'soft', label: '寄宿家庭', test: p => p.offer === 'school' || !p.limits.includes('noHostFamily'), gap: '需要认可 sponsor 匹配的寄宿家庭，且你排除了寄宿家庭。' },
      { kind: 'soft', label: '接受短期', test: p => !p.limits.includes('noShortStay'), gap: '这是一种有限期文化交流安排，不适合想直接获得长期身份的人。' },
    ] }],
    steps: ['确认年龄和国籍资格', '通过认可 sponsor 匹配寄宿家庭', '核对家庭任务、小时数、零用金和保险', '由 sponsor 处理居留流程', '在许可范围内完成互惠安排'],
    documents: ['护照', '个人背景材料', '寄宿家庭协议', '保险与健康 / 品格材料'],
    pitfalls: ['Au Pair 不是普通保姆工签，不能在家庭外随意打工。', '寄宿家庭关系和合同要写清任务、休息和终止安排。', '结束后的身份没有自动延续。'],
    faq: [{ q: '可以把 Au Pair 当作低成本工作吗？', a: '不应这样理解，它是有严格边界的文化交流居留，主要收益不是工资。' }],
    attribution: { inspirationSource: 'https://overseas-pathways.pages.dev/pathways/netherlands-au-pair/', sourceType: 'secondary-reference', notAuthoritative: true },
  },
  {
    id: 'ship-crew', country: '全球 / 多国', flag: '⚓', region: 'global',
    title: '国际船员 / 邮轮工作', officialName: 'Seafarer employment',
    type: 'employment', legalNature: 'employment', tags: ['高中可查', '培训考证', '工作强度高'],
    summary: '通过海事培训、体检和船员招聘进入邮轮或货轮工作。它是雇佣路线，不是“拿船员证就能移民”。',
    requirements: { age: '参考页列 18–45 岁', education: '高中及以上常见', language: '邮轮岗位通常需基础英语', stage: '学生 / 毕业生均可了解', offer: '需船公司或合法派遣安排' },
    costs: { currency: '人民币 / 美元', proofOfFunds: '培训与出发前生活费', tuition: '基础安全培训和考证费用', visaFee: '视航线、船旗国和岗位', startup: '参考页估算约 8,000–20,000 元，逐项核实' },
    timeline: { preparation: '培训与证件约 1–2 个月，找船时间不同', processing: '取决于船公司和航线', duration: '合同常见 6–9 个月，按合同轮休' },
    workRights: '按船员合同、船旗国和靠港规则工作。', workRestrictions: '工作时间长、生活封闭；海员证不等于任何国家的普通工作许可。', followOn: '合同续签和职业晋升取决于船公司、证件和资历。', quota: '由船公司岗位需求决定。',
    officialLinks: [{ label: '中国海事局', url: 'https://www.msa.gov.cn/' }, { label: '国际海事组织 IMO', url: 'https://www.imo.org/' }],
    secondaryLinks: [{ label: '参考路径页（海外路径）', url: 'https://overseas-pathways.pages.dev/pathways/ship-crew/' }],
    verifiedAt: '2026-09', confidence: 'needs-confirmation',
    branches: [{ id: 'crew', label: '船员雇佣', checks: [
      { kind: 'hard', label: '年龄', test: p => p.age >= 18 && p.age <= 45, gap: '年龄可能不在参考招聘窗口内，按船公司核实。' },
      { kind: 'soft', label: '工作安排', test: p => ['employer', 'training'].includes(p.offer), gap: '需要合法船公司 / 派遣机构的岗位安排，不能只买培训课程。' },
      { kind: 'soft', label: '接受高强度工作', test: p => !p.limits.includes('noManual'), gap: '船上工作通常长工时、封闭且体力消耗大。' },
    ] }],
    steps: ['确定邮轮、货轮或其他船员岗位', '核验船公司 / 派遣机构资质', '完成海员体检与 B01–B04 等培训', '取得海员证、服务簿和岗位合同', '核对船旗国、靠港身份和保险安排', '按合同工作并保留工资、工伤和遣返条款'],
    documents: ['护照', '海员体检', '无犯罪记录（按要求）', '培训与海员证件', '正式雇佣合同'],
    pitfalls: ['船员证件不等于普通国家的工作签证。', '高额培训费、押金和“保证上船”是常见风险。', '合同必须写清薪资、保险、工伤和遣返责任。'],
    faq: [{ q: '没有航海经验能做吗？', a: '部分邮轮服务岗位可能接受新人，但必须通过正规招聘和培训。' }],
    attribution: { inspirationSource: 'https://overseas-pathways.pages.dev/pathways/ship-crew/', sourceType: 'secondary-reference', notAuthoritative: true },
  },
  {
    id: 'georgia-long-stay', country: '格鲁吉亚', flag: '🇬🇪', region: 'europe',
    title: '格鲁吉亚长期停留 / 落脚', officialName: 'Visa-free / residence options',
    type: 'longStay', legalNature: 'longStay', tags: ['低门槛落脚', '不是工作许可', '先体验'],
    summary: '更像一个低门槛落脚和观察选项，而不是学生或工作签证。免签停留绝不能自动理解成可以合法就业。',
    requirements: { age: '无统一年龄门槛', education: '通常无学历门槛', language: '按生活和工作实际需要', stage: '适合过渡期', offer: '不需要学校录取' },
    costs: { currency: '美元 / 拉里', proofOfFunds: '按入境与居留要求', tuition: '无统一课程', visaFee: '按具体身份', startup: '生活费和保险另算' },
    timeline: { preparation: '短', processing: '按实际身份', duration: '免签停留期限与居留方案分别核实' },
    workRights: '只有取得相应工作 / 居留许可后，才讨论合法工作。', workRestrictions: '免签停留不是工作许可。', followOn: '需另行研究居留、工作或学习身份。', quota: '按入境规则。',
    officialLinks: [{ label: '格鲁吉亚领事信息', url: 'https://geoconsul.gov.ge/en/visaInformation' }],
    secondaryLinks: [{ label: '参考路径页（海外路径）', url: 'https://overseas-pathways.pages.dev/pathways/georgia-slow/' }],
    verifiedAt: '2026-09', confidence: 'review',
    branches: [{ id: 'stay', label: '合法停留', checks: [{ kind: 'soft', label: '合法身份', test: p => true, gap: '需确认你的停留身份是否允许工作，不能把免签当工签。' }] }],
    steps: ['核对中国护照当前入境规则', '准备住宿、保险和返程 / 后续计划', '如要工作或长期住，单独申请对应许可', '不要在访问身份下从事未经许可的工作'],
    documents: ['护照', '住宿与保险材料', '资金和返程安排'],
    pitfalls: ['低门槛不等于有职业发展和永居路径。', '任何“落地后随便工作”的说法都要先查法律。'],
    faq: [{ q: '可以把它当作移民吗？', a: '不能直接这样理解；它更适合被标记为落脚或考察选项。' }],
    attribution: { inspirationSource: 'https://overseas-pathways.pages.dev/pathways/georgia-slow/', sourceType: 'secondary-reference', notAuthoritative: true },
  },
  {
    id: 'thailand-long-stay', country: '泰国', flag: '🇹🇭', region: 'asia',
    title: '泰国低成本长期停留', officialName: 'Long-stay options',
    type: 'longStay', legalNature: 'longStay', tags: ['生活成本相对低', '身份选择多', '工作需另查'],
    summary: '适合先体验生活方式和区域环境，但不同长期停留身份差异极大，不能把旅游停留、DTV 和工作许可混为一谈。',
    requirements: { age: '按具体身份', education: '按具体身份', language: '按生活与工作实际', stage: '不局限学生', offer: '视身份' },
    costs: { currency: '泰铢 / 人民币', proofOfFunds: '部分身份需要存款或收入', tuition: '无统一', visaFee: '按签证类别', startup: '生活费、保险和续签成本另算' },
    timeline: { preparation: '按身份', processing: '按使领馆和电子签流程', duration: '按具体签证' },
    workRights: '必须按具体签证确认，长期停留不自动授予工作权。', workRestrictions: '旅游、访问和部分长期停留身份不能随意工作。', followOn: '后续路径取决于身份类别和雇主 / 收入条件。', quota: '按具体项目。',
    officialLinks: [{ label: '泰国电子签证官方平台', url: 'https://www.thaievisa.go.th/' }],
    secondaryLinks: [{ label: '参考路径页（海外路径）', url: 'https://overseas-pathways.pages.dev/pathways/thailand-slow/' }],
    verifiedAt: '2026-09', confidence: 'needs-confirmation',
    branches: [{ id: 'stay', label: '长期停留', checks: [{ kind: 'soft', label: '身份类别', test: p => true, gap: '先确定具体签证类别，再核对它是否允许工作或学习。' }, { kind: 'soft', label: '预算', test: p => p.cash !== 'under1', gap: '需要准备保险、住宿和续签成本。' }] }],
    steps: ['明确是旅游、学习、远程工作还是本地就业', '在官方平台选择对应签证类别', '核对工作权、收入 / 存款与保险要求', '按身份边界停留，别把体验签当工作签'],
    documents: ['护照', '资金 / 收入材料', '保险与住宿材料', '具体签证要求的补充文件'],
    pitfalls: ['“长期住”与“合法工作”是两件事。', '项目营销页面常把多个身份混写，必须回到官方类别。'],
    faq: [{ q: '泰国长期停留能不能工作？', a: '要看具体身份；没有对应工作许可，就不能把远程或本地工作想当然地算合法。' }],
    attribution: { inspirationSource: 'https://overseas-pathways.pages.dev/pathways/thailand-slow/', sourceType: 'secondary-reference', notAuthoritative: true },
  },
  {
    id: 'wwoof-global', country: '全球 / 多国', flag: '🌱', region: 'global',
    title: 'WWOOF 农场换宿', officialName: 'World Wide Opportunities on Organic Farms',
    type: 'platform', legalNature: 'platform', tags: ['平台线索', '不是签证', '换宿'],
    summary: '连接农场与志愿者的平台。平台本身不发签证、不授予工作许可，任何换宿安排都要先确认你在目标国的合法身份。',
    requirements: { age: '按平台和农场', education: '通常无统一学历要求', language: '按 host 沟通', stage: '学生可短期了解', offer: '需要 host 接受' },
    costs: { currency: '当地货币', proofOfFunds: '按入境身份', tuition: '平台会员 / 交通等', visaFee: '平台不发签证', startup: '机票、保险和生活费自负' },
    timeline: { preparation: '找 host 与确认身份', processing: '不是签证审理', duration: '按 host 协议' },
    workRights: '平台安排不等于工作许可；先确认目标国入境身份允许什么。', workRestrictions: '不要用旅游 / 免签身份从事当地法律禁止的劳动。', followOn: '没有自动身份衔接。', quota: '平台和 host 自行安排。',
    officialLinks: [{ label: 'WWOOF 官方', url: 'https://wwoof.net/' }],
    secondaryLinks: [{ label: '参考路径页（海外路径）', url: 'https://overseas-pathways.pages.dev/pathways/wwoof-global/' }],
    verifiedAt: '2026-09', confidence: 'review',
    branches: [{ id: 'platform', label: '平台线索', checks: [{ kind: 'soft', label: '身份核验', test: p => false, gap: '这是平台，不是签证；必须自行核对目标国的合法入境和工作权限。' }, { kind: 'soft', label: '接受农业', test: p => !p.limits.includes('noManual'), gap: '换宿通常包含农场或户外劳动，而你排除了这类工作。' }] }],
    steps: ['查看目标国家入境与工作法律', '在平台了解 host、任务、住宿和评价', '书面确认劳动时长、食宿和退出安排', '以合法身份入境，不把平台注册当签证'],
    documents: ['护照', '保险', 'host 协议和紧急联系人', '目标国允许的入境 / 工作许可'],
    pitfalls: ['平台不是签证机关。', '“志愿者”标签不能自动让劳动合法。', '保留 host 沟通、费用和任务记录。'],
    faq: [{ q: 'WWOOF 能不能让我合法工作？', a: '不能自动做到；平台只提供匹配，合法工作权取决于目标国法律和你的身份。' }],
    attribution: { inspirationSource: 'https://overseas-pathways.pages.dev/pathways/wwoof-global/', sourceType: 'secondary-reference', notAuthoritative: true },
  },
  {
    id: 'helpx-workaway', country: '全球 / 多国', flag: '🛠️', region: 'global',
    title: 'HelpX / Workaway 换宿平台', officialName: 'Work exchange platforms',
    type: 'platform', legalNature: 'platform', tags: ['平台线索', '不是签证', '食宿交换'],
    summary: '换宿和志愿项目平台，不是移民项目。它可以帮你找到 host，但不能替你解决签证、劳动许可和保险。',
    requirements: { age: '按平台与 host', education: '通常无统一要求', language: '按 host 沟通', stage: '适合短期体验', offer: 'host 接受' },
    costs: { currency: '美元 / 欧元 / 当地货币', proofOfFunds: '按目标国要求', tuition: '会员费和交通', visaFee: '平台不发签证', startup: '保险与生活费另算' },
    timeline: { preparation: '先确认身份，再联系 host', processing: '无签证审理', duration: '按 host 协议' },
    workRights: '平台撮合不代表取得工作许可。', workRestrictions: '访问身份、免签身份和志愿安排的边界必须核实。', followOn: '没有自动身份升级。', quota: '按平台 / host。',
    officialLinks: [{ label: 'HelpX', url: 'https://www.helpx.net/' }, { label: 'Workaway', url: 'https://www.workaway.info/' }],
    secondaryLinks: [{ label: '参考路径页（海外路径）', url: 'https://overseas-pathways.pages.dev/pathways/helpx-workaway/' }],
    verifiedAt: '2026-09', confidence: 'review',
    branches: [{ id: 'platform', label: '平台线索', checks: [{ kind: 'soft', label: '身份核验', test: p => false, gap: '这是平台，不是签证；必须先确认目标国身份和工作许可。' }, { kind: 'soft', label: '接受换宿', test: p => !p.limits.includes('noManual'), gap: '换宿通常会涉及家务、农场或户外任务。' }] }],
    steps: ['核对目标国合法身份', '阅读 host 的任务、时长和住宿条件', '保留书面记录与紧急方案', '不要为“平台会员”支付所谓签证或保过费用'],
    documents: ['护照', '保险', 'host 约定', '合法入境与工作许可证明（如需要）'],
    pitfalls: ['平台不是签证，也不保证 host 质量。', '换宿劳动是否合规要看当地法律。', '拒绝高额押金、签证费和“内部 host”话术。'],
    faq: [{ q: '换宿适合想长期移民的人吗？', a: '更适合短期体验和了解当地生活，不能把它当作长期身份路线。' }],
    attribution: { inspirationSource: 'https://overseas-pathways.pages.dev/pathways/helpx-workaway/', sourceType: 'secondary-reference', notAuthoritative: true },
  },
];

function validateStudentData() {
  const problems = [];
  const ids = new Set();
  const validTypes = new Set(Object.keys(STUDENT_TYPES));
  const validRegions = new Set(Object.keys(STUDENT_REGIONS));
  for (const p of STUDENT_PATHWAYS) {
    if (ids.has(p.id)) problems.push(`重复 id: ${p.id}`);
    ids.add(p.id);
    for (const k of ['country', 'title', 'type', 'legalNature', 'summary', 'officialLinks', 'verifiedAt', 'confidence', 'branches']) {
      if (!p[k]) problems.push(`${p.id} 缺少 ${k}`);
    }
    if (!validTypes.has(p.type)) problems.push(`${p.id} type 未定义: ${p.type}`);
    if (!validRegions.has(p.region)) problems.push(`${p.id} region 未定义: ${p.region}`);
    if (!p.officialLinks?.length) problems.push(`${p.id} 缺官方链接`);
    for (const l of [...(p.officialLinks || []), ...(p.secondaryLinks || [])]) {
      if (!/^https:\/\//.test(l.url)) problems.push(`${p.id} 链接不是 HTTPS: ${l.url}`);
    }
    if (!p.branches?.every((b) => b.id && b.checks?.length)) problems.push(`${p.id} 分支结构不完整`);
    for (const b of p.branches || []) {
      for (const c of b.checks || []) {
        if (!['hard', 'soft'].includes(c.kind)) problems.push(`${p.id}/${b.id} gate kind 无效`);
        if (typeof c.test !== 'function') problems.push(`${p.id}/${b.id} gate 缺 test`);
      }
    }
  }
  return problems;
}
